### ISSUE TITLE
Cannot prune models with tensorflow operations

### ISSUE THREAD

**Issue by netrauser** [tensorflow/model-optimization#1051]
Prior to filing: check that this should be a bug instead of a feature request. Everything supported, including the compatible versions of TensorFlow, is listed in the overview page of each technique. For example, the overview page of quantization-aware training is [here](https://www.tensorflow.org/model_optimization/guide/quantization/training). An issue for anything not supported should be a feature request.

**Describe the bug**
Cannot prune models with tensor flow operations

**System information**
Ubuntu 20.04

TensorFlow version (installed from source or binary):  2.11.0 (binary)

TensorFlow Model Optimization version (installed from source or binary): 0.7.3 (binary)

Python version: 3.7

**Describe the expected behavior**
I have created tensorflow keras model with functional api and the model has  tensorflow operations  layers in it. when pruning the model usint tfmot the expectation was to prune the weights of the model 

**Describe the current behavior**
Currently its not pruning the model and giving out this error 

`ValueError: Please initialize `Prune` with a supported layer. Layers should either be supported by the PruneRegistry (built-in keras layers) or should be a `PrunableLayer` instance, or should has a customer defined `get_prunable_weights` method. You passed: <class 'keras.layers.core.tf_op_layer.TFOpLambda'>`

**Code to reproduce the issue**
```
import numpy as np
from tensorflow.keras.models import Model
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow.keras.layers import Input, Dense

inputs = Input(shape=(5, 3))
a = tf.reduce_max(inputs, axis=1)
b = Dense(10)(a)
c = tf.expand_dims(b, axis=2)
model = Model(inputs,c)

# predict
print(model.predict(np.random.random((2,5,3))))

prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude

# Compute end step to finish pruning after 2 epochs.
batch_size = 128
epochs = 2
validation_split = 0.1 # 10% of training set will be used for validation set. 

num_images = 10 * (1 - validation_split)
end_step = np.ceil(num_images / batch_size).astype(np.int32) * epochs

# Define model for pruning.
pruning_params = {
      'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(initial_sparsity=0.50,
                                                               final_sparsity=0.80,
                                                               begin_step=0,
                                                               end_step=end_step)
}

model_for_pruning = prune_low_magnitude(model, **pruning_params)

# `prune_low_magnitude` requires a recompile.
model_for_pruning.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model_for_pruning.summary()

```

**Additional context**
I have tried these solution https://github.com/keras-team/keras/issues/16889 and  https://github.com/tensorflow/model-optimization/issues/374 but does not seem to work
```
import keras
from tensorflow_model_optimization.sparsity.keras import PrunableLayer
class PruneOpLambda(keras.layers.core.tf_op_layer.TFOpLambda, PrunableLayer):
    def get_prunable_weights(self):
        return []
```

**Comment by tink-expo** [comment]
Hello, could you elaborate on what you got after you tried the solution of extending both TFOpLamda and PrunableLayer? From the initial error msg it seems that it would be the solution we can try. Did you get the same error msg or did you encouter another error?

**Comment by netrauser** [comment]
I am getting the same error , this is the full code

```
import keras
from tensorflow_model_optimization.sparsity.keras import PrunableLayer
class PruneOpLambda(keras.layers.core.tf_op_layer.TFOpLambda, PrunableLayer):
    def get_prunable_weights(self):
        return []

import numpy as np
from tensorflow.keras.models import Model
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow.keras.layers import Input, Dense

inputs = Input(shape=(5, 3))
a = tf.reduce_max(inputs, axis=1)
b = Dense(10)(a)
c = tf.expand_dims(b, axis=2)
model = Model(inputs,c)

# predict
print(model.predict(np.random.random((2,5,3))))

prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude

# Compute end step to finish pruning after 2 epochs.
batch_size = 128
epochs = 2
validation_split = 0.1 # 10% of training set will be used for validation set. 

num_images = 10 * (1 - validation_split)
end_step = np.ceil(num_images / batch_size).astype(np.int32) * epochs

# Define model for pruning.
pruning_params = {
      'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(initial_sparsity=0.50,
                                                               final_sparsity=0.80,
                                                               begin_step=0,
                                                               end_step=end_step)
}

model_for_pruning = prune_low_magnitude(model, **pruning_params)

# `prune_low_magnitude` requires a recompile.
model_for_pruning.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model_for_pruning.summary()
```

**Comment by chococigar** [comment]
Hi netrauser,

I believe you have to use the model / layer initiated with your  customer defined get_prunable_weights.

For example, this works:

`
import numpy as np
from tensorflow.keras.models import Model
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow.keras.layers import Input, Dense
from tensorflow_model_optimization.python.core.sparsity.keras import prunable_layer
import keras
# from tensorflow_model_optimization.sparsity.keras import PrunableLayer

class PruneTFOpLambda(keras.layers.core.tf_op_layer.TFOpLambda, prunable_layer.PrunableLayer):
    def get_prunable_weights(self):
        return []

prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude

# Compute end step to finish pruning after 2 epochs.
batch_size = 128
epochs = 2
validation_split = 0.1 # 10% of training set will be used for validation set. 

num_images = 10 * (1 - validation_split)
end_step = np.ceil(num_images / batch_size).astype(np.int32) * epochs

# Define model for pruning.
pruning_params = {
      'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(initial_sparsity=0.50,
                                                               final_sparsity=0.80,
                                                               begin_step=0,
                                                               end_step=end_step)
}

def dummy_func(a, b):
    return a + b

prune_low_magnitude(PruneTFOpLambda(dummy_func), **pruning_params)
`

Please also refer to this colab guide: [link](https://colab.corp.google.com/google_src/files/head/depot/google3/third_party/tensorflow_model_optimization/opensource/g3doc/guide/pruning/comprehensive_guide.ipynb#scrollTo=BLgH1aFMjTK4)

**Comment by christian-steinmeyer** [comment]
I had a similar issue with `tf.nn.space_to_depth`, just tried your approach and found that pruning the model works, but stripping the prune wrappers doesn't. Any idea why that might be?

```py
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow.keras.layers import Input, Dense
from tensorflow_model_optimization.python.core.sparsity.keras import prunable_layer
import keras


class PruneTFOpLambda(keras.layers.core.tf_op_layer.TFOpLambda, prunable_layer.PrunableLayer):
    def get_prunable_weights(self):
        return []


if __name__ == '__main__':
    prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude

    # Define model for pruning.
    pruning_params = {
        'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(
            initial_sparsity=0.50, final_sparsity=0.80, begin_step=0, end_step=1
        )
    }
    custom_space_to_depth = PruneTFOpLambda(tf.nn.space_to_depth)
    inputs = Input(shape=(None, 10, 10))
    x = custom_space_to_depth(inputs, 2)
    model = tf.keras.models.Model(inputs, x)

    pruned_model = prune_low_magnitude(model, **pruning_params)

    cleaned_model = tfmot.sparsity.keras.strip_pruning(pruned_model)  # <-- fails with error message below
```

The error message I get is
```
Shape must be rank 4 but is rank 5 for '{{node tf.nn.space_to_depth/SpaceToDepth}} = SpaceToDepth[T=DT_FLOAT, block_size=2, data_format="NHWC"](tf.nn.space_to_depth/SpaceToDepth/input)' with input shapes: [1,?,?,10,10].

Call arguments received by layer "tf.nn.space_to_depth" (type PruneTFOpLambda):
  • input=['tf.Tensor(shape=(None, None, 10, 10), dtype=float32)']
  • block_size=2
  • data_format=NHWC
  • name=None

**Comment by netrauser** [comment]
@christian-steinmeyer try replacing tensorflow operations with keras operations, for example instead of useing`tf.nn.space_to_depth` use `tf.keras.layers.Reshape`

**Comment by christian-steinmeyer** [comment]
Thanks for the suggestion.
I ended up, using a slightly more generic approach based on [this suggestion](https://github.com/tensorflow/model-optimization/issues/972).


```py
def prepare_model_for_pruning(
    model: tf.keras.models.Model, pruning_params: dict[str, Any]
) -> tf.keras.models.Model:
    def apply_pruning_to_supported_layers(layer):
        if (
            PruneRegistry.supports(layer)
            or isinstance(layer, tfmot.sparsity.keras.PrunableLayer)
            or hasattr(layer, 'get_prunable_weights')
        ):
            return tfmot.sparsity.keras.prune_low_magnitude(layer, **pruning_params)
        return layer

    return tf.keras.models.clone_model(
        model,
        clone_function=apply_pruning_to_supported_layers,
    )
