### ISSUE TITLE
Support of Tensorflow 2.0

### ISSUE THREAD

**Issue by katmatus** [tensorflow/model-optimization#11]
Do you plan to support Tensorflow 2.0?

**Comment by liyunlu0618** [comment]
Yes. We are actively working on this.

**Comment by iamsaksham** [comment]
@liyunlu0618 Any update on when it will be released?

**Comment by alanchiao** [comment]
@katmatus, @iamsaksham : please follow https://github.com/tensorflow/model-optimization/issues/172

We are currently working on this, including testing on training on production models such as mobilenet.

**Comment by alanchiao** [comment]
@katmatus, @iamsaksham : support has now been added and released.

**Comment by lgeiger** [comment]
> support has now been added and released.

That's great! Though it looks like this only holds for the pruning API, or am I missing something? Do you have an estimated timeline for quantization aware training support for TF 2.x to share?

**Comment by alanchiao** [comment]
@lgeiger : we're still actively working on quantization aware training support for TF 2.x via Keras APIs (when launched, there will be a release and the docs [here](https://www.tensorflow.org/model_optimization/guide/quantization) will be updated). Timeline wise it's hard to say still but hopefully within a month or two of next year.

**Comment by lgeiger** [comment]
@alanchia Thanks for the update :+1:

**Comment by alanchiao** [comment]
@lgeiger: in case you didn't see, Keras TF 2.0 QAT has been launched.
