### ISSUE TITLE
A error about quantization aware training

### ISSUE THREAD

**Issue by panhu** [tensorflow/model-optimization#1105]
Prior to filing: check that this should be a bug instead of a feature request. Everything supported, including the compatible versions of TensorFlow, is listed in the overview page of each technique. For example, the overview page of quantization-aware training is [here](https://www.tensorflow.org/model_optimization/guide/quantization/training). An issue for anything not supported should be a feature request.

**Describe the bug**
When i want to use quantization aware training,the code is:

quan_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model),

and the error is:

File "../../../keras/src/saving/legacy/serialization.py",line 536,in deserialize_keras_object
     obj = module_objects.get(object_name)
AttibuteError:"NoneType" object has no attribute 'get'
**System information**

TensorFlow version 2.13.1:

TensorFlow Model Optimization version 0.7.5(installed from source):

Python version: 3.8

**Comment by lenscloth** [comment]
Hello @panhu, 

Would you mind providing us a reproducible code such that we can identify the problem?

**Comment by panhu** [comment]
Thanks,Due to tf version issues and solutions
