### ISSUE TITLE
Model optimization without tensorflow lite

### ISSUE THREAD

**Issue by datavisornicolacorradi** [tensorflow/model-optimization#118]
I'd like to optimized a pre-trained model without converting it to tensorflow lite.

I'm dealing with a variable-sized input which standard tensorflow handles fine but this function (as well as other) is not (yet?) supported by tensorflow lite. Can I just optimize the model without converting it to tf-lite?

Tensorflow lite actually seems to optimize the graph before the conversion (`_run_graph_optimizations`  is called before the actual conversion), but I couldn't find any documentation regarding this.

**Comment by alanchiao** [comment]
Hi. Can you be more specific on the kinds of optimizations you are looking for?

For instance: for the pruning technique (benefits described at https://www.tensorflow.org/model_optimization/guide/pruning), you can see [here]( https://colab.sandbox.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/pruning/pruning_with_keras.ipynb#scrollTo=GhXHuBAGOBvY) that there are compression benefits on the Keras model, prior to conversion to TFLite.

**Comment by bothrasumit** [comment]
@alanchiao while trying to convert TF model into TFlite, Is pruning necessary? or we can directly convert into TFlite model?

**Comment by alanchiao** [comment]
@bothrasumit : pruning is not necessary. It is a form of optimization. You can directly convert to TFLite without it.

**Comment by alanchiao** [comment]
Closing since no response to my question. @datavisornicolacorradi: please reopen if you'd like to follow up .
