### ISSUE TITLE
hassan

### ISSUE THREAD

**Issue by malook665** [tensorflow/model-optimization#170]
**Describe the bug**

**System information**

TensorFlow installed from (source or binary):
TensorFlow version (use command below):
TensorFlow Model Optimization version:
Python version:

**Describe the expected behavior**

**Describe the current behavior**

**Code to reproduce the issue**
Provide a reproducible code that is the bare minimum necessary to generate the
problem.

**Screenshots**

**Additional context**

**Comment by malook665** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **System information**
> 
> TensorFlow installed from (source or binary):
> TensorFlow version (use command below):
> TensorFlow Model Optimization version:
> Python version:
> 
> **Describe the expected behavior**
> 
> **Describe the current behavior**
> 
> **Code to reproduce the issue**
> Provide a reproducible code that is the bare minimum necessary to generate the
> problem.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by alanchiao** [comment]
@malook665 : did you file this accidentally?
