### ISSUE TITLE
version issue (Python)

### ISSUE THREAD

**Issue by dariaAlium** [tensorflow/model-optimization#175]
**Describe the bug**
Hello everyone, the problem with the versions in Python due to inept manipulations, as a result, I can’t install the libraries using cmd and Pycharm IDE, as well as the launch itself through Pycharm.Hello everyone, the problem with the versions in Python due to inept manipulations, as a result, I can’t install the libraries using cmd and Pycharm IDE, as well as the launch itself through Pycharm.
I tried to clean all the Python files from the computer (including from path), but I can not delete the python.exe and python3.exe files at C: Users / darku / AppData / Local / Microsoft / WindowsApps.
When deleting everything except these two files, cmd at the python command redirects to the Misrosoft Store with a request to purchase Python 3.7.5

I downloaded and installed Python 3.7.5 as a result of cmd with the python command you can write codes. The pip version is the latest. Some libraries, for example, numpy, can be installed, and some, for example, pymorphy2, can not.
*******************
`ERROR: Command errored out with exit status 1:
     command: 'c:\users\darku\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\darku\\AppData\\Local\\Temp\\pip-install-s6sp3zyv\\pymorphy\\setup.py'"'"'; __file__='"'"'C:\\Users\\darku\\AppData\\Local\\Temp\\pip-install-s6sp3zyv\\pymorphy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pip-egg-info
         cwd: C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pymorphy\morph.py", line 2, in <module>
        from pymorphy_speedups._morph import *
    ModuleNotFoundError: No module named 'pymorphy_speedups'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\setup.py", line 14, in <module>
        from pymorphy.version import __version__
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pymorphy\__init__.py", line 1, in <module>
        from pymorphy.morph import get_morph
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pymorphy\morph.py", line 10, in <module>
        from pymorphy._morph import *
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pymorphy\_morph.py", line 6, in <module>
        from pymorphy.constants import *
      File "C:\Users\darku\AppData\Local\Temp\pip-install-s6sp3zyv\pymorphy\pymorphy\constants.py", line 83, in <module>
        RU_TENSES_STANDARD.items() + RU_VOICES_STANDARD.items())
    TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by markol4691** [comment]
To much for one day😜

**Comment by alanchiao** [comment]
This seems like an issue that isn't tied to the Model Optimization library itself. If that's not the case, please add additional information that would suggest otherwise. 

Closing due to the above. Please reopen otherwise and I suggest you go to stackoverflow if it's not tied to Model Optimization.
