### ISSUE TITLE
What is the difference between tf-mot and tensorrt?

### ISSUE THREAD

**Issue by jusonn** [tensorflow/model-optimization#199]
Now I am considering model optimization with tf2.0 model.

And there is tfmot, which is pretty new but made by tf itself. Also, there is tensorrt made by nvidia.

I wonder what is the difference between them and why TF team started to make this project.

**Comment by alanchiao** [comment]
I'll give some initial thoughts and added Raziel to comment officially. 

First off, the notion of model optimization is not new and has been around for quite a while. Quantization, for instance, has existed in TF for years, but the most recent launches / libraries are more robust, have wider model coverage, and have different ways to use that are easier. Some libraries that were previously in tf.contrib are being replaced. 

Second, TFMOT and TensorRT often work together. For instance, if you look at the [docs here](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#quantization-training), TRT actually makes a reference to quantization-aware training, which is a component of tfmot. 

Third, remember that there is a much a wide range of hardware out there (from microcontrollers to mobile to the server-side GPUs and the new accelerators).  Having general model optimization support in TF means that all hardware can reap its benefits.

**Comment by alanchiao** [comment]
Going to close since it's been a bit. @jusonn: if you have followup on my point. Feel free to reopen.
