### ISSUE TITLE
Deprecation of Python 2

### ISSUE THREAD

**Issue by alanchiao** [tensorflow/model-optimization#211]
See https://python3statement.org/ and other related sites. 

Internally, we currently run most unit tests on both Python 2 and 3. We will eventually turn down Python 2 support, with a target release version here to be posted here. 

Update the API compatibility docs once this is done.

**Comment by alanchiao** [comment]
@nutsiepully, @PraChetit FYI.

**Comment by alanchiao** [comment]
It's notable that TensorFlow 2.1.0 is the last release of TF that supports Python 2 (see [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0)). In other words, the Keras Quantization API (which relies on a version > 2.1.0) will not be able to support Python 2 off-the-bat. For the Keras pruning API, we have to determine when to deprecate Python 2 support.

**Comment by nutsiepully** [comment]
I think Python2 code will be able to link with Python3 code just fine. So even if our code is in python2, and running on TF with python3, it should just work. I agree we should deprecate it over time, just that I don't think having unit tests for both 2 and 3 shouldn't cause any concerns in the meanwhile.

**Comment by alanchiao** [comment]
The last release to support Python 2 was made in https://github.com/tensorflow/model-optimization/releases/tag/v0.4.0.

The appropriate changes to the BUILD files were made [here](https://github.com/tensorflow/model-optimization/pull/485) and to setup.py [here](https://github.com/tensorflow/model-optimization/pull/495).

Marking this as resolved. There is still cleanup needed to get rid of Python 2 specific code.
