### ISSUE TITLE
Pruning not working for tf.keras.Batchnorm

### ISSUE THREAD

**Issue by jkparuchuri** [tensorflow/model-optimization#224]
**Describe the bug**
ValueError: Please initialize `Prune` with a supported layer. Layers should either be a `PrunableLayer` instance, or should be supported by the PruneRegistry. You passed: <class 'tensorflow.python.keras.layers.normalization.BatchNormalization'>

**System information**

TensorFlow installed from (source or binary): binary

TensorFlow version: 2.1.0

TensorFlow Model Optimization version: 0.2.1

Python version: 3.5.6

**Comment by alanchiao** [comment]
@jkparuchuri : how are your creating your batchnorm layer? In 2.1.0, the batchnorm layer class should be tensorflow.python.keras.layers.normalization_v2.BatchNormalization if you are using tf.keras.layers.BatchNormalization.

**Comment by alanchiao** [comment]
Making a documentation update in https://github.com/tensorflow/model-optimization/pull/225.

**Comment by jkparuchuri** [comment]
@alanchiao  Building from source not working on my mac

ITs giving error ERROR: no such target '//tensorflow_model_optimization:pip_pkg': target 'pip_pkg' not declared in package 'tensorflow_model_optimization' defined by /Users/jith/june/git/model-optimization/tensorflow_model_optimization/BUILD.
INFO: Elapsed time: 0.083s

**Comment by alanchiao** [comment]
Can you cd out of tensorflow_model_optimization into the model-optimization folder? Then run the same command.

I realized that the `cd tensorflow_model_optimization` instruction is incorrect. Should say `cd model_optimization`.

**Comment by jkparuchuri** [comment]
@alanchiao  Tried that but its giving different errors

ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:63:1: //tensorflow_model_optimization/python/core/clustering/keras:cluster_test: no such attribute 'python_version' in 'py_test' rule.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:75:1: //tensorflow_model_optimization/python/core/clustering/keras:clustering_centroids_test: no such attribute 'python_version' in 'py_test' rule.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:87:1: //tensorflow_model_optimization/python/core/clustering/keras:cluster_wrapper_test: no such attribute 'python_version' in 'py_test' rule.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:103:1: //tensorflow_model_optimization/python/core/clustering/keras:clustering_registry_test: no such attribute 'python_version' in 'py_test' rule.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:9:1: Target '//tensorflow_model_optimization/python/core/clustering/keras:cluster' contains an error and its package is in error and referenced by '//tensorflow_model_optimization/python/core/clustering/keras:keras'.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/keras/BUILD:9:1: Target '//tensorflow_model_optimization/python/core/clustering/keras:__init__.py' contains an error and its package is in error and referenced by '//tensorflow_model_optimization/python/core/clustering/keras:keras'.
ERROR: /Users/jith/june/git/model-optimization/tensorflow_model_optimization/python/core/clustering/BUILD:5:1: Target '//tensorflow_model_optimization/python/core/clustering/keras:keras' contains an error and its package is in error and referenced by '//tensorflow_model_optimization/python/core/clustering:clustering'.
ERROR: Analysis of target '//:pip_pkg' failed; build aborted: Loading failed.
INFO: Elapsed time: 0.136s

**Comment by alanchiao** [comment]
python_version is available in bazel since 0.22.0 (see https://docs.bazel.build/versions/0.22.0/be/python.html). Do you think you'd be able to upgrade your version of bazel? I'll need to take a look at the TFMOT docs and clarify the minimum bazel version also.

**Comment by jkparuchuri** [comment]
@alanchiao  Thankyou, upgrading bazel resolved the building from source. But still see the same error :(

'PruneRegistry. You passed: {input}'.format(input=layer.__class__))
ValueError: Please initialize `Prune` with a supported layer. Layers should either be a `PrunableLayer` instance, or should be supported by the PruneRegistry. You passed: <class 'tensorflow.python.keras.layers.normalization.BatchNormalization'>

**Comment by alanchiao** [comment]
I'd make sure that the tensorflow_model_optimization you're using is the one built from https://github.com/tensorflow/model-optimization#installing-from-source with your change as opposed to the one you previously installed that MOT provided. I'm pretty confident what I suggested was correct.

**Comment by jkparuchuri** [comment]
@alanchiao  Able to resolve the issue.  Its "tf.compat.v1.keras.layers.BatchNormalization: []". keras was missing earlier.

**Comment by Craftsman381** [comment]
Trying to prune Resnet50 and getting this error, can you tell me what't the solution of this.
```
ValueError: Please initialize `Prune` with a supported layer. Layers should either be a `PrunableLayer` instance, or should be supported by the PruneRegistry. You passed: <class 'tensorflow.python.keras.layers.normalization.BatchNormalization'>```

**Comment by jkparuchuri** [comment]
@Craftsman381   Workaround is to add `"tf.compat.v1.keras.layers.BatchNormalization: []"` to prune_registry at https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/sparsity/keras/prune_registry.py#L82 and rebuild from source

**Comment by Craftsman381** [comment]
@jkparuchuri in which dictionary I have to add it **_RNN_CELLS_WEIGHTS_MAP** or in **_LAYERS_WEIGHTS_MAP**
