### ISSUE TITLE
Does TF-MOT quantization will keep use tfLiteConverter?

### ISSUE THREAD

**Issue by jusonn** [tensorflow/model-optimization#236]
I just noticed that quantization guide in tf-mot is using tfLite Converter.
Then, will TF-MOT library will partially use TF-Lite?

**Comment by alanchiao** [comment]
Hi @jusonn 

In general, TFMOT is working to make our tools backend-agnostic (meaning support TensorFlow, TFLite, and other ones also).

We will be launching a tool for quantization-aware training soon. TensorRT mentions its predecessor, contrib.quantize, in its [docs](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#quantization-nodes).

**Comment by alanchiao** [comment]
For a while, the post-training quantization tools will be available only through TFLite. Again, we working to generalize it.

Closing and feel free to reopen and if you don't think your question is fully answered.
