### ISSUE TITLE
The example does not work,  got a error: 'QuantizeAwareActivation' object has no attribute '__name__'

### ISSUE THREAD

**Issue by CristXu** [tensorflow/model-optimization#295]
Hi,
    After run the code to save the model, it complaints that: 'QuantizeAwareActivation' object has no attribute '__name__'; So I add a self.__name__ = ‘’ to the line 107 of quantize_aware_activation.py and i can save the model.  But i think this is not a legal way to solve the issue.
  and My env is : tensorflow-gpu == 1.14.0 and the tensorflow_model_optimazation == 0.2.1 compiled from the newest github's code
  Thanks for your help

Regards

**Comment by alanchiao** [comment]
Please follow the bug template and as a part of it, provide a fully reproducible example (including a model).

It's not specific enough to know which "example" you are referring to.

1.14.0 will also not be supported at launch. Only 2.0+
