### ISSUE TITLE
Another error when covert the model to tflite:  Unknown activation function:

### ISSUE THREAD

**Issue by CristXu** [tensorflow/model-optimization#296]
tf.keras.models.save_model(model, model_name, include_optimizer=False)
# Convert to TFLite model.
with quantize.quantize_scope():
  converter = tf.lite.TFLiteConverter.from_keras_model_file(
      model_name)

**Comment by alanchiao** [comment]
Please follow the bug template and as a part of it, provide a fully reproducible example (including a model).
