### ISSUE TITLE
run quantize mnist_cnn.py  errors

### ISSUE THREAD

**Issue by aa12356jm** [tensorflow/model-optimization#300]
**Describe the bug**

**System information** ubuntu18,04

TensorFlow installed from (source or binary):binary

TensorFlow version:tf-nightly 2.2.0-dev20200316

TensorFlow Model Optimization version:tf-model-optimization-nightly-0.2.1.dev20200317

Python version:3.7

**Describe the expected behavior**
get the correct tflite quant model

**Describe the current behavior**
converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 484, in from_keras_model
    if not isinstance(model.call, _def_function.Function):
AttributeError: 'str' object has no attribute 'call'

**Code to reproduce the issue**
Provide a reproducible code that is the bare minimum necessary to generate the
problem.

```
from __future__ import print_function

import tensorflow as tf  # pylint: disable=g-bad-import-order

from tensorflow_model_optimization.python.core.quantization.keras import quantize

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

if tf.keras.backend.image_data_format() == 'channels_first':
  x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
  x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
  input_shape = (1, img_rows, img_cols)
else:
  x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
  x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
  input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

l = tf.keras.layers

model = tf.keras.Sequential([
    quantize.quantize_annotate_layer(
        l.Conv2D(32, 5, padding='same', activation='relu',input_shape=input_shape)),
    l.MaxPooling2D((2, 2), (2, 2), padding='same'),
    quantize.quantize_annotate_layer(
        l.Conv2D(64, 5, padding='same', activation='relu')),
    l.MaxPooling2D((2, 2), (2, 2), padding='same'),
    l.Flatten(),
    quantize.quantize_annotate_layer(l.Dense(1024, activation='relu')),
    l.Dropout(0.4),
    quantize.quantize_annotate_layer(l.Dense(num_classes)),
    # TODO(alanchiao): fuse softmax once we've handled it.
    l.Softmax(),
])

model = quantize.quantize_apply(model)

# Dump graph to /tmp for verification on tensorboard.
graph_def = tf.compat.v1.get_default_graph().as_graph_def()
with open('/tmp/mnist_model.pbtxt', 'w') as f:
  f.write(str(graph_def))

model.compile(
    loss=tf.keras.losses.categorical_crossentropy,
    optimizer=tf.keras.optimizers.Adadelta(),
    metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

# Export to Keras.
keras_file = './train_models/quantized_mnist.h5'
tf.keras.models.save_model(model, keras_file)
tf.keras.models.save_model(model, "./train_models/epoch12_quant/",save_format='tf')

# Convert to TFLite model.
with quantize.quantize_scope():
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0]: (0., 255.)}  # mean, std_dev
tflite_model = converter.convert()
open('./train_models/quantized_mnist.tflite', 'wb').write(tflite_model)
```

**Screenshots**

**Additional context**

**Comment by CristXu** [comment]
Hi，
     I think that your tf version is not compatible with the example's, the needed version is tf 1.14.0; you use  
      converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
    to load the keras_models, but the from_keras_model need a keras_model file, not the model-path,
you need to use **from_keras_model_file** insead

**Comment by aa12356jm** [comment]
> Hi，
> I think that your tf version is not compatible with the example's, the needed version is tf 1.14.0; you use
> converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
> to load the keras_models, but the from_keras_model need a keras_model file, not the model-path,
> you need to use **from_keras_model_file** insead

the example is  not compatible with tf2.x ?  i dont read that the example is just for tf 1.14.0, where is the declare?

**Comment by CristXu** [comment]
> > Hi，
> > I think that your tf version is not compatible with the example's, the needed version is tf 1.14.0; you use
> > converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
> > to load the keras_models, but the from_keras_model need a keras_model file, not the model-path,
> > you need to use **from_keras_model_file** insead
> 
> the example is not compatible with tf2.x ? i dont read that the example is just for tf 1.14.0, where is the declare?

Chinese ok？
我从他使用的api推断的，因为他使用的是tf.lite.TFLiteConvert.from_keras_model_file, 这个是tf1.14的API，tf 2.0没有这个了，而且，你会发现如果切换tf2.0运行还会报错，还需要添加tf.enable_eager_execution() 这个也是tf.1.14中的

**Comment by CristXu** [comment]
Hi，
     我觉得你也是中国人，咱们可以中文交流。。。。我回复你了，我通过他的api和一系列的报错推断的

**Comment by aa12356jm** [comment]
你用tf.1.14.0可以得到量化后的tflite文件吗？我用tf1.14.0训练后转换tflite也会有问题

**Comment by CristXu** [comment]
不可以啊，，，，我提了两个issue，一个是模型无法加载，一个是模型无法转化； 您可以看我提的前两个；我后来用了tf.compat.v2， 可以转出来，但是仿佛结果不对，因为我发现relu层转出的结果竟然不是大于0，我觉得他那套脚本有问题，等待官方解答吧

**Comment by aa12356jm** [comment]
thanks

**Comment by alanchiao** [comment]
Hey! We'll be sure to fix the example after. mnist_cnn.py is out of date right now. 

The quantized_input_stats API is deprecated and our new Keras tools currently only support TF 2.X+.

**Comment by CristXu** [comment]
Hi,
       thanks very much for your help， and I have re-edited my issue on github just a moment ago.

**Comment by alanchiao** [comment]
@CristXu : 

> 但是仿佛结果不对，因为我发现relu层转出的结果竟然不是大于0

Could you provide instructions to reproduce (all the way to printing out the ReLU layer output in TFLite)?

**Comment by CristXu** [comment]
Hi，
       The test.py is my test code for quant-aware training with a cifar10 dataset. The quantized.tflite is the quantized model in tflite format, the cifar10_ds3.h5 is the raw keras model.
       By the way, 您能看懂中文？

Regards

**Comment by alanchiao** [comment]
@CristXu : I don't have access to the files you mentioned. It could be that since you are not replying by email, the files aren't being attached.

I can understand Chinese but it's best to communicate in English here because a lot of the developers cannot understand Chinese. Thanks!

**Comment by alanchiao** [comment]
Edit: you are not replying by email -> you are replying by email

**Comment by CristXu** [comment]
Hi，
       Ok，I have attached a *.zip to the github

Regards

**Comment by alanchiao** [comment]
I see the files.

> the output of the relu layer is not bigger than 0

Is this the first ReLU layer from test.py? How did you print the output of the layer in TFLite? I ask both to reproduce and because the printing logic may not have been correct.

**Comment by CristXu** [comment]
For the first question: Yes, it is the first relu layer, and you can also see that all the output of the relu layer inside the model are not bigger than 0.
The second: Sorry, I do not know how to print the output of the layer in TFLite. I often use the netron-tool to see the inside of the model(the weights or the output scale) instead, not with an API. And by the way, I only know how to print the output of the layer with keras.
And, maybe the netron has  something wrong to show the output value?

**Comment by alanchiao** [comment]
> netron-tool

Got it, so you are seeing the values via netron. We're almost there. I can run the model on netron myself, but I want to make sure I understand what -0.599 and 0.599 came from.

Are they the values of the FakeQuant min/max values? Or the actual outputs themselves?

If you can share a screenshot/image of netron showing -0.599 to 0.599, then I have everything needed to reproduce and fix the issue if there is one.

**Comment by CristXu** [comment]
Sorry, the -0.599 and 0.599 are just an example(a rounding value, the true value is -5.988006114959717 ≤ q ≤ 5.989650249481201), Wait a moment, I will take a screenshot to you

**Comment by alanchiao** [comment]
Thanks Crist for the images. 

I tried the Netron tool and got the same thing as you.

The -0.599 and 0.599 are in fact the min/max values and not the outputs of the ReLU layer. We are not passing any inputs to the model, so Netron isn't executing anything on TFLite and producing actual outputs. 

When you actually run the model as a quantized one, you'll find that the output of ReLU to still be greater than 0.

**Comment by alanchiao** [comment]
That said, the FakeQuant min value should ideally never be below 0 still for ReLU. It is right now since we've initialized the min value to be -6. I am working on a PR that will initialize the min value more intelligently, but even without it, you can get good results (we've checked on mobilenet v1/v2 and resnet).

**Comment by CristXu** [comment]
Thank you very much, But honestly, it really confused me a lot before… now I know why this happen, thanks.
And I have another issue has updated below https://github.com/tensorflow/model-optimization/issues/308
The main issue is that: I can not use a tf.v1’s API to load a quantized model, and I need to
Modify a source code of the tensorflow-optimization project which way I think is a tricky way…

Another question is that: how can I set some convert-parameters into the model, such as
# input_arrays = converter.get_input_arrays()
# converter.quantized_input_stats = {input_arrays[0]: (0., 255.)}  # mean, std_dev
As you said before, these lines is deprecated now, how can I use it on the tf.v2?

Regards
