### ISSUE TITLE
module 'tensorflow_model_optimization' has no attribute 'quantization' 

### ISSUE THREAD

**Issue by mahdichtourou24051994** [tensorflow/model-optimization#341]
**Describe the bug**
module 'tensorflow_model_optimization' has no attribute 'quantization' 

**System information**

TensorFlow installed from (source or binary): binary

TensorFlow version: 2.1.0

TensorFlow Model Optimization version: 0.2.1

Python version: colab version

**Describe the expected behavior**
import the model as described in guide
**Describe the current behavior**
not able to import the model 
**Code to reproduce the issue**
import tensorflow_model_optimization as tfmot
quantize_model = tfmot.quantization.keras.quantize_model

**Screenshots**
![image](https://user-images.githubusercontent.com/62559820/78595056-a4242780-7849-11ea-9069-9b4bcc6a052e.png)

**Additional context**

**Comment by alanchiao** [comment]
@mahdichtourou24051994: the official 0.3.0 release that has the API is not released yet.

The quantization API has not been launched yet. 

Please wait until https://github.com/tensorflow/tensorflow/issues/27880 is closed prior to trying it.
