### ISSUE TITLE
How to convert a model (trained with quantization awareness) to int8?

### ISSUE THREAD

**Issue by suttergustavo** [tensorflow/model-optimization#349]
I've being trying to convert a model trained with quantization awareness to a .tflite file that only uses int8 operations. I modified the [quantization aware training example from guide](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide) adding the following lines before the conversion (as I would do in a usual conversion):

```
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

converter.representative_dataset = representative_data_gen

# Added the next 3 lines
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

quant_tflite_model = converter.convert()
file = open('quant_aware_model.tflite', 'wb')
file.write(quant_tflite_model)
```

However it raises the following error:

`RuntimeError: Max and min for dynamic tensors should be recorded during calibration`

I've checked the documentation but didn't find any example of how to perform this operation. Is it supported?

**Comment by alanchiao** [comment]
For documentation on what's supported, please refer to https://www.tensorflow.org/model_optimization/guide/quantization/training

Inside it, you'll find a link to an issue for your question on full-integer

**Comment by alanchiao** [comment]
The page above hasn't quite updated yet: for today, please refer to https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training.md.

**Comment by suttergustavo** [comment]
Great, I'll check! Thanks you!

**Comment by alanchiao** [comment]
If you think it's too hard to find your answer in the above documentation and have thoughts, welcome any suggestions.

**Comment by EscVM** [comment]
@suttergustavo 

I have the same problem! Have you found a solution?

I have a model trained with quantization aware. I followed the official [TensorFlow guide](https://tensorflow.google.cn/model_optimization/guide/quantization/training_example), where is written "After this, you have an actually quantized model with int8 weights and uint8 activations."

converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()

The conversion works, but at the edge tpu complier says that the model is not quantized:

"
Edge TPU Compiler version 2.1.302470888
Invalid model: bin/srmodel_full_integer_qaware.tflite
Model not quantized
"

**Comment by UsingtcNower** [comment]
I have the same problem! After converter.convert(), the error is : Cannot set tensor: Got value of type UINT8 but expected type FLOAT32.
