### ISSUE TITLE
Layer up_sampling2d_36:<class 'tensorflow.python.keras.layers.convolutional.UpSampling2D'> is not supported. ou can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.

### ISSUE THREAD

**Issue by Craftsman381** [tensorflow/model-optimization#372]
**Describe the bug**
I am trying to use quantize_model() to optimise UNET model, which contains UpSampling2D layer and conversion of this layer is not supported by tensorflow_model_optimization right now.

**System information**
MacOS Catalina
Version: 10.15.2 

TensorFlow installed from (source or binary):
binary

TensorFlow version:
2.1.0

TensorFlow Model Optimization version:
0.3.0

Python version:
3.7.4

**Describe the expected behavior**
Successfully quantize UpSampling2D layer.

**Describe the current behavior**
No support right now to quantize UpSampling2D layer.

**Code to reproduce the issue**
Provide a reproducible code that is the bare minimum necessary to generate the
problem.

```
def unet(pretrained_weights = None,input_size = (256,256,1)):

    inputs = Input(shape=input_size)
    conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(inputs)
    conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv1)

    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
    conv2 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool1)
    conv2 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv2)

    pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)
    conv3 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool2)
    conv3 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv3)

    pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)
    conv4 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool3)
    conv4 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv4)
    drop4 = Dropout(0.5)(conv4)

    pool4 = MaxPooling2D(pool_size=(2, 2))(drop4)
    conv5 = Conv2D(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(pool4)
    conv5 = Conv2D(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv5)
    drop5 = Dropout(0.5)(conv5)

    up6 = Conv2D(512, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(drop5))
    merge6 = concatenate([drop4,up6], axis = 3)
    conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge6)
    conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv6)

    up7 = Conv2D(256, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv6))
    merge7 = concatenate([conv3,up7], axis = 3)
    conv7 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge7)
    conv7 = Conv2D(256, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv7)

    up8 = Conv2D(128, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv7))
    merge8 = concatenate([conv2,up8], axis = 3)
    conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge8)
    conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv8)

    up9 = Conv2D(64, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv8))
    merge9 = concatenate([conv1,up9], axis = 3)
    conv9 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge9)
    conv9 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv9)
    conv9 = Conv2D(2, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv9)
    conv10 = Conv2D(1, 1, activation = 'sigmoid')(conv9)

    model = Model(inputs = inputs, outputs = conv10)
    model.compile(optimizer = Adam(lr = 1e-4), loss = dice_coef_loss,metrics = [dice_coef])
    
    #model.summary()

    if(pretrained_weights):
    	model.load_weights(pretrained_weights)

    return model

model = unet()
quantize_model = tfmot.quantization.keras.quantize_model
q_aware_model = quantize_model(model)
```

**Additional context**
--------------------------
Error produced by this [file](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize.py) line no 372.

RuntimeError: Layer up_sampling2d_40:<class 'tensorflow.python.keras.layers.convolutional.UpSampling2D'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.

**Comment by Mohit-Ak** [comment]
I am facing exactly the same issue today while trying to implement _unet_ for Coral Edge_TPU.

Following are the findings-
- I tried using the Conv2DTranspose instead of upsampling but it looks like Conv2DTranspose is also not supported.
``` Layer conv2Dtranspose:<class 'tensorflow.python.keras.layers.convolutional.Conv2DTranspose'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.```
- Most of the [official example quantized models of Edge TPU ](https://github.com/google-coral/tflite/tree/master/python) do not need upscaling of the image. Their output is either a class or a number of bounding boxes with the class.
- Although there are examples of models [Deeplabv3 based quantized edgetpu segmentation](https://github.com/google-coral/edgetpu/blob/master/test_data/deeplabv3_mnv2_pascal_quant_edgetpu.tflite), there is no help regarding the architecture and how the upscaling has been solved.
- Similar unresolved yet [closed old issue.](https://github.com/google-coral/edgetpu/issues/31).

Any help in this regard will be greatly appreciated.

**Comment by haozha111** [comment]
@suharshs Could you help take a look at this issue?

**Comment by Craftsman381** [comment]
@Mohit-Ak These optimization techniques are new in TF 2, hopefully they are going to add support in the next update.

**Comment by Mohit-Ak** [comment]
> @Mohit-Ak These optimization techniques are new in TF 2. You should try `quantize_annotate_layer` API still if it not work for you then you should try tf-nightly. If this support is not present in tf-nightly too then you have to open this issue and they will add support in next release.

- I am using TF-nightly 2.2.0-dev20200423.
- Although I have not tried `quantize_annotate_layer`, I assume, If I quantize all the layers except for the UpSampling2D/Conv2DTranspose layers, then the `edgetpu-compiler` throws an error stating "model not quantized". 
- I had tried this earlier, where I only quantized a bunch of layers and not the whole model and fed it into the `edgetpu-compiler` to get the "model not quantized" error.

UPDATE

I tried using the resize_images function for instead of UpSampling2D but gave me the same error.

```
def resize_image(inp,  s, data_format):
    try:
        return Lambda(lambda x: keras.backend.resize_images(x,
                                                height_factor=s[0],
                                                width_factor=s[1],
                                                data_format=data_format,
                                                interpolation='bilinear'))(inp)
```

**Comment by nutsiepully** [comment]
Hi @Mohit-Ak @Craftsman381,

Thanks for the great feedback. We haven't added support for `Upsampling2D` and `Conv2DTranspose` yet. We are ramping up support for layers based on feedback from users. So thank you for that. Most of these layers are quite simple, and haven't been added due to conversion support.

`Upsampling2D` doesn't actually need any QAT handling. You can try passing a [NoOpQuantizeConfig](https://github.com/tensorflow/model-optimization/blob/d328a642d74de85ac8d4213dfe122b94a7cbc554/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_configs.py#L44) to it as the `QuantizeConfig` and the training should just work. Let us know if the conversion has issues.

As for `Conv2DTranspose`, we still have to add support. But we can now prioritize it with this feedback. Thanks!

**Comment by alanchiao** [comment]
@Craftsman381: FYI if your goal is to run UpSampling2D eventually in TFLite, the TFLite converter may not be able to convert it yet. You'll need to see if someone has filed an issue on github.com/tensorflow/tensorflow and request for it.

In general, the comments from testQuantizeSingleLayer_ProducesFullIntegerModel_TF2 in [this test file](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize_functional_test.py#L266) suggest why they have not been added yet. UpSampling2D is under the comment "# Not done since TFLite converter doesn't support in TF2 yet", though things may have changed since.

**Comment by OriAlpha** [comment]
How can we use quantize_annotate_layer API is there any example for this

**Comment by mlinxiang** [comment]
> Hi @Mohit-Ak @Craftsman381,
> 
> Thanks for the great feedback. We haven't added support for `Upsampling2D` and `Conv2DTranspose` yet. We are ramping up support for layers based on feedback from users. So thank you for that. Most of these layers are quite simple, and haven't been added due to conversion support.
> 
> `Upsampling2D` doesn't actually need any QAT handling. You can try passing a [NoOpQuantizeConfig](https://github.com/tensorflow/model-optimization/blob/d328a642d74de85ac8d4213dfe122b94a7cbc554/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_configs.py#L44) to it as the `QuantizeConfig` and the training should just work. Let us know if the conversion has issues.
> 
> As for `Conv2DTranspose`, we still have to add support. But we can now prioritize it with this feedback. Thanks!

`tfmot.quantization.keras.QuantizeConfig` instance.You passed an instance of type: ABCMeta.

**Comment by ianholing** [comment]
Same point that @mlinxiang here. 
```
import tensorflow_model_optimization as tfmot
from tensorflow_model_optimization.python.core.quantization.keras.default_8bit import default_8bit_quantize_configs
...
u = tfmot.quantization.keras.quantize_annotate_layer(
                UpSampling2D(size=size_divider), quantize_config=default_8bit_quantize_configs.NoOpQuantizeConfig) (u)
```

And get the same error:
`quantize_config` can only be a `tfmot.quantization.keras.QuantizeConfig` instance.You passed an instance of type: ABCMeta.

**Comment by ianholing** [comment]
Finally I get it working with a workaround:

```
import tensorflow_model_optimization as tfmot
from tensorflow_model_optimization.python.core.quantization.keras import quantize_config

###   Clone NoOpQuantizeConfig locally   ###
class NoOpQuantizeConfig(quantize_config.QuantizeConfig):
    """QuantizeConfig which does not quantize any part of the layer."""
    def get_weights_and_quantizers(self, layer):
        return []
    def get_activations_and_quantizers(self, layer):
        return []
    def set_quantize_weights(self, layer, quantize_weights):
        pass
    def set_quantize_activations(self, layer, quantize_activations):
        pass
    def get_output_quantizers(self, layer):
        return []
    def get_config(self):
        return {}

quantize_config = NoOpQuantizeConfig()

...

###   Wrap your upsampling layer with this   ###
u = tfmot.quantization.keras.quantize_annotate_layer(
                UpSampling2D(size=size_divider), quantize_config=quantize_config) (layer_input)

...

###     And then just compile and use   ###
with tf.keras.utils.custom_object_scope({'NoOpQuantizeConfig': NoOpQuantizeConfig}):
            quantized_model = tfmot.quantization.keras.quantize_model(generate_model())
            quantized_model.summary()
```

In my case it is a functional Model, but I'm pretty sure it also works with Sequentials.

**Comment by nutsiepully** [comment]
@ianholing @mlinxiang - As long as the object you pass subclasses `QuantizeConfig`, it should work.

@ianholing - In your sample code, consider using `quantize_scope`. It also adds all the other quant related objects in scope.

**Comment by holokai-ai** [comment]
@nutsiepully @alanchiao Looks like the TFLite Hexagon DSP Delegate already supports these quantized up-sampling ops:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md
- Resize Bilinear
- Resize Nearest Neighbor
- TransposeConv2D

But I believe none of the above are currently supported by TF2 TFMOT model quantizer.  Please correct me if I'm wrong.  Then how can one generate a TFLite mode that uses these quantized up-sampling operations?

Thanks

**Comment by holokai-ai** [comment]
Inspecting Google's [quantized EdgeTPU DeepLab v3 segmentation model](https://github.com/google-coral/edgetpu/blob/master/test_data/deeplabv3_mnv2_pascal_quant_edgetpu.tflite) that @Mohit-Ak mentioned in this thread, looks like the model has a custom MobileNet v2 backbone plus a few ResizeBilinear ops to up-scale the tensors, among other things.   Diagram below.

How does one use TFMOT to map to quantization-friendly up-scaling ops like the ones used in this EdgeTPU model?

Thanks

![image](https://user-images.githubusercontent.com/61851501/84698752-33fae780-af05-11ea-933a-ab50e1d08820.png)

**Comment by EscVM** [comment]
@holokai-ai 

How did you wrap 'tf.image.resize()' in the Keras model? Thanks

**Comment by EscVM** [comment]
> Finally I get it working with a workaround:
> 
> ```
> import tensorflow_model_optimization as tfmot
> from tensorflow_model_optimization.python.core.quantization.keras import quantize_config
> 
> ###   Clone NoOpQuantizeConfig locally   ###
> class NoOpQuantizeConfig(quantize_config.QuantizeConfig):
>     """QuantizeConfig which does not quantize any part of the layer."""
>     def get_weights_and_quantizers(self, layer):
>         return []
>     def get_activations_and_quantizers(self, layer):
>         return []
>     def set_quantize_weights(self, layer, quantize_weights):
>         pass
>     def set_quantize_activations(self, layer, quantize_activations):
>         pass
>     def get_output_quantizers(self, layer):
>         return []
>     def get_config(self):
>         return {}
> 
> quantize_config = NoOpQuantizeConfig()
> 
> ...
> 
> ###   Wrap your upsampling layer with this   ###
> u = tfmot.quantization.keras.quantize_annotate_layer(
>                 UpSampling2D(size=size_divider), quantize_config=quantize_config) (layer_input)
> 
> ...
> 
> ###     And then just compile and use   ###
> with tf.keras.utils.custom_object_scope({'NoOpQuantizeConfig': NoOpQuantizeConfig}):
>             quantized_model = tfmot.quantization.keras.quantize_model(generate_model())
>             quantized_model.summary()
> ```
> 
> In my case it is a functional Model, but I'm pretty sure it also works with Sequentials.
> If everything goes right, you can see in your summary every layer with the "quant_" prefix.

I've tried your solution, but I had this error 'ValueError: Unknown object: NoOpQuantizeConfig'

**Comment by holokai-ai** [comment]
> @holokai-ai
> 
> How did you wrap 'tf.image.resize()' in the Keras model? Thanks

@EscVM  -- I'm not wrapping tf.image.resize() at the moment; I'm simply calling it intermixed with Keras layers, in a functional style.

**Comment by EscVM** [comment]
> > @holokai-ai
> > How did you wrap 'tf.image.resize()' in the Keras model? Thanks
> 
> @EscVM -- I'm not wrapping tf.image.resize() at the moment; I'm simply calling it intermixed with Keras layers, in a functional style.

Ah ok! Indeed, it works. Thanks

**Comment by EscVM** [comment]
@holokai-ai 

The problem is that if you need to use the Edge TPU compiler 'tf.image.resize()' is not compatible :)

**Comment by holokai-ai** [comment]
> @holokai-ai
> 
> The problem is that if you need to use the Edge TPU compiler 'tf.image.resize()' is not compatible :)

That's precisely why I posed the question in this thread to @alanchiao 
 and @nutsiepully --- 

**For those of us who need to do edge inference on hardware that requires integer-only ops like EdgeTPU and Hexagon DSP, how can we map to quantization-friendly TFLite up-sampling ops?**    

Clearly Google has a way to do this (e.g. with the quantized ResizeBilinear in DeepLab v3 segmentation model running on EdgeTPU).

**Comment by EscVM** [comment]
> > @holokai-ai
> > The problem is that if you need to use the Edge TPU compiler 'tf.image.resize()' is not compatible :)
> 
> That's precisely why I posed the question in this thread to @alanchiao
> and @nutsiepully ---
> 
> **For those of us who need to do edge inference on hardware that requires integer-only ops like EdgeTPU and Hexagon DSP, how can we map to quantization-friendly TFLite up-sampling ops?**
> 
> Clearly Google has a way to do this (e.g. with the quantized ResizeBilinear in DeepLab v3 segmentation model running on EdgeTPU).


On this purpose it would be useful to have 'depth_to_space' :)) 

Anyway, about bilinear, I was thinking of training with your method and then make a little bit of surgery and substitute 'tf.image.resize()' with the 'UpSampling2D' Keras layer. I theory should work because bilinear doesn't make use of variables.

**Comment by holokai-ai** [comment]
> > > @holokai-ai
> > > The problem is that if you need to use the Edge TPU compiler 'tf.image.resize()' is not compatible :)
> > 
> > 
> > That's precisely why I posed the question in this thread to @alanchiao
> > and @nutsiepully ---
> > **For those of us who need to do edge inference on hardware that requires integer-only ops like EdgeTPU and Hexagon DSP, how can we map to quantization-friendly TFLite up-sampling ops?**
> > Clearly Google has a way to do this (e.g. with the quantized ResizeBilinear in DeepLab v3 segmentation model running on EdgeTPU).
> 
> On this purpose it would be useful to have 'depth_to_space' :))
> 
> Anyway, about bilinear, I was thinking of training with your method and then make a little bit of surgery and substitute 'tf.image.resize()' with the 'UpSampling2D' Keras layer. I theory should work because bilinear doesn't make use of variables.

@alanchiao @nutsiepully  --  FWIW I tried the following hack:
- reverted back to UpSampling2D() instead of tf.image.resize()
- for UpSampling2D(), tired both interpolation="nearest" and interpolation="bilinear"
- hacked one line in the TFMOT code to accept UpSampling2D():

```
holokai@deckard:~/model-optimization$ git diff
diff --git a/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_registry.py b/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_registry.py
index 433128f..d8bc1a1 100644
--- a/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_registry.py
+++ b/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_registry.py
@@ -97,7 +97,7 @@ class QuantizeRegistry(quantize_registry.QuantizeRegistry, _RNNHelper):
       _no_quantize(layers.Cropping2D),
       _no_quantize(layers.Cropping3D),
       # _no_quantize(layers.UpSampling1D),
-      # _no_quantize(layers.UpSampling2D),
+      _no_quantize(layers.UpSampling2D),
       # _no_quantize(layers.UpSampling3D),
       _no_quantize(layers.ZeroPadding1D),
       _no_quantize(layers.ZeroPadding2D),
```

The resulting model trained well on our task in Python TensorFlow, both for FP32 (96.1%) and INT8 QAT (94.8%).

However when I benchmarked the resulting TFLite model on our hardware, it blew up, so something went terribly bad in the TFLite conversion process:
```
msm8996:/data/local/tmp # taskset 0f ./benchmark_model \
    --use_hexagon=true \
    --input_layer=images \
    --input_layer_shape=1,224,224,1 \
    --graph=test-bifpn-qat-int8.tflite

...
...
Loaded model efficientnet-lite0-bifpn-qat-int8.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libadsprpc.so
INFO: Created TensorFlow Lite delegate for Hexagon.
INFO: Hexagon delegate: 78 nodes delegated out of 138 nodes with 4 partitions.

Applied Hexagon delegate, and the model graph will be partially executed w/ the delegate.
The input model file size (MB): 3.64997
Initialized session in 384.2ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
----------------
Timestamp: Wed Jan 21 02:10:46 1970


Log
hexagon/ops/src/op_input.c:153:out 1 too small (128 < 50176)
hexagon/src/execute.c:142:execute() failed on node id=1 err=-1
hexagon/src/interface.c:1270:fail in execute_inner()

----------------
ERROR: Failed: Failed to execute graph.. STATE: FAILED_TO_EXECUTE_GRAPH
ERROR: Node number 140 (TfLiteHexagonDelegate) failed to invoke.

----------------
<Lots of repeated errors above>
...
...

count=16 first=48883 curr=29973 min=29841 max=48883 avg=31238.4 std=4558

Benchmarking failed.
```

**Comment by nutsiepully** [comment]
@mlinxiang, @ianholing - Your code was failing since you were using `NoOpQuantizeConfig` which is a class, and not `NoOpQuantizeConfig()` which is the object.

In
```
import tensorflow_model_optimization as tfmot
from tensorflow_model_optimization.python.core.quantization.keras.default_8bit import default_8bit_quantize_configs
...
u = tfmot.quantization.keras.quantize_annotate_layer(
                UpSampling2D(size=size_divider), quantize_config=default_8bit_quantize_configs.NoOpQuantizeConfig) (u)
```
you should replace `NoOpQuantizeConfig` with `NoOpQuantizeConfig()`.

**Comment by nutsiepully** [comment]
Hi @holokai-ai , @EscVM,

Thanks for the detailed feedback and report.

We pulled out `UpSampling2D` support prior to launch since we hadn't tested it end to end  (including conversion) and wanted to ensure numerical accuracy before releasing it. In the meanwhile, the best way to work around it is to use the approach both of you have used so far - which is providing a custom `QuantizeConfig` for the layer.

If you provide a config which is correct, and conversion is supported the the code should work and the TFLite model should just run.

For nearest neighbor interpolation, `NoOpQuantizeConfig` is the correct solution. And the patch above which uncomments the line is enough. For resize bilinear, there needs to be additional work to match the TFL kernel implementation correctly.

I'll be taking some time out to work on it. If you are interested in contributing a patch, I'm happy to help :)

@holokai-ai, it's not clear to me why you are having trouble on your hardware. I was able to run a QAT model with `UpSampling2D` locally with TFLite interpreter running on CPU. Perhaps, the delegate code isn't handling ResizeBilinear correctly.

**Comment by holokai-ai** [comment]
> I'll be taking some time out to work on it. If you are interested in contributing a patch, I'm happy to help :)
> 
> @holokai-ai, it's not clear to me why you are having trouble on your hardware. I was able to run a QAT model with `UpSampling2D` locally with TFLite interpreter running on CPU. Perhaps, the delegate code isn't handling ResizeBilinear correctly.

@nutsiepully Thank you very much for taking the time to look into supporting quantized up-sampling ops!   We need those ops to run modern detection and segmentation networks, and we need them quantized for edge hardware that require integer-only ops.

I would imagine that Nearest Neighbor interpolation would be the easiest to support, because I believe there's no quantization involved; just copying bytes.

Yes, the fact that the QAT model with `UpSampling2D()` works on CPU, but not DSP, might point to an issue with the DSP Delegate.    However, I did mention earlier in this thread that I had a QAT model running with `tf.image.resize()`, and the DSP Delegate gracefully handled that non-quantized op that by falling back to CPU, and not crashing like `UpSampling2D()`.   So it may still be an issue with the conversion process to TFLite.

**Comment by nutsiepully** [comment]
It's possible there might be an issue.

Once I get the time, I'll add support for `UpSampling2D` to ensure it can convert to TFLite, and ensure numerically stable execution on TFLite. Once that is in place, you can re-run the code and try the DSP delegate.

If there's still an issue, we can dig in further.

**Comment by EscVM** [comment]
@nutsiepully @holokai-ai 

I used your code to wrap the model and it worked just fine:

```
def annotate(layer):
    if layer._name.startswith('up_sampling2d'):
        return layer   # pass thru; don't quantize tf.image.resize()
    # quantize everything else
    return tfmot.quantization.keras.quantize_annotate_layer(layer)

annotated_model = tf.keras.models.clone_model(model, clone_function=annotate)

quantized_model = tfmot.quantization.keras.quantize_apply(annotated_model)
```

However, when I try to convert with TFLite

```
converter = tf.lite.TFLiteConverter.from_keras_model(quantized_model)


converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
```

I got the following error:

RuntimeError: Quantization not yet supported for op: 

Do you know how to proceed?

**Comment by EscVM** [comment]
On [this](https://www.tensorflow.org/model_optimization/guide/quantization/training_example) guide is written "After this, you have an actually quantized model with int8 weights and uint8 activations."

```
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()
```

The conversion works, but at the edge tpu complier says that the model is not quantized:

"
Edge TPU Compiler version 2.1.302470888
Invalid model: bin/srmodel_full_integer_qaware.tflite
Model not quantized
"

**Comment by kevinyamauchi** [comment]
Thanks for the great discussion, everyone! This issue has been helpful for my debugging!

> As for Conv2DTranspose, we still have to add support. But we can now prioritize it with this feedback. Thanks!

@nutsiepully , `Conv2DTranspose` would be super useful to me as well (for the same reasons as stated above by @Mohit-Ak). Is there an ETA for adding QAT support? I believe it is already possible to quantize with TFLite and it is supported on EdgeTPU. I would be happy to help with this, but I would need some guidance. Would it be helpful to make a separate feature request issue for Conv2DTranspose QAT support?


> The conversion works, but at the edge tpu complier says that the model is not quantized:

@EscVM , [this issue](https://github.com/tensorflow/tensorflow/issues/38285) discusses setting the input/output type when converting to an integer quantized TFLite model. While it appears that it doesn't currently support QAT, this comment on converting the input/output to `int8`or `uint8` might help solve that: https://github.com/tensorflow/model-optimization/issues/431#issuecomment-646109974.

**Comment by EscVM** [comment]
> Hi @holokai-ai , @EscVM,
> 
> Thanks for the detailed feedback and report.
> 
> We pulled out `UpSampling2D` support prior to launch since we hadn't tested it end to end (including conversion) and wanted to ensure numerical accuracy before releasing it. In the meanwhile, the best way to work around it is to use the approach both of you have used so far - which is providing a custom `QuantizeConfig` for the layer.
> 
> If you provide a config which is correct, and conversion is supported the the code should work and the TFLite model should just run.
> 
> For nearest neighbor interpolation, `NoOpQuantizeConfig` is the correct solution. And the patch above which uncomments the line is enough. For resize bilinear, there needs to be additional work to match the TFL kernel implementation correctly.
> 
> I'll be taking some time out to work on it. If you are interested in contributing a patch, I'm happy to help :)
> 
> @holokai-ai, it's not clear to me why you are having trouble on your hardware. I was able to run a QAT model with `UpSampling2D` locally with TFLite interpreter running on CPU. Perhaps, the delegate code isn't handling ResizeBilinear correctly.

Thank you @nutsiepully for your help. Can you provide an example of a possible custom `QuantizeConfig` for the UpSampling2D layer?

**Comment by thnkim** [comment]
Did anyone find a solution for this? I have the same problem.

**Comment by Lotte1990** [comment]
I would also like to quantize the UpSampling2D layer. @nutsiepully Any updates on this?

**Comment by DiscretePython** [comment]
I've run into this problem as well. I believe this is the only layer stopping QAT for my detection model. Any updates?

**Comment by sunzhe09** [comment]
I met the same problem

**Comment by fengxiuyaun** [comment]
I met the same problem

**Comment by limbtio** [comment]
Is there any update on the Conv2DTranspose QAT support?

I'm working with version 2.5.0-dev20201123, and getting this error:
RuntimeError: Layer decoder_stage0a_transpose:<class 'tensorflow.python.keras.layers.convolutional.Conv2DTranspose'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.

**Comment by Xhark** [comment]
@limbtio Now we supports TransposeConv: https://github.com/tensorflow/model-optimization/commit/4f4e5d02db5424d5cfcb822a8965023bf8d2011e

But it also requires up-to-date TFLite kernel: https://github.com/tensorflow/tensorflow/commit/f98a42d0a09cb71a9d2e6f36a4cbc29389ee5483

Please report a bug if you have any problem with it.

**Comment by bayesian-mind** [comment]
@Xhark I am still having issues with the ResizeBilinear Layer using the `tf.image.resize` or `tf.keras.layers.Resizing`. Are these layers going to be addressed too? I checked the PR and the code and did not find anything solving these layers.

**Comment by sunzhe09** [comment]
when I use QAT to training transposeconv2d，after I get the tflite，there is an tanspose layer before transposeconv2d. Is this a bug?can this   tanspose layer be folded?

**Comment by sunzhe09** [comment]
![image](https://user-images.githubusercontent.com/30410113/153374985-d99fb655-2abc-44e8-9cdf-402cccc7082f.png)

**Comment by DuJiahao1996** [comment]
> Hi @Mohit-Ak @Craftsman381,
> 
> Thanks for the great feedback. We haven't added support for `Upsampling2D` and `Conv2DTranspose` yet. We are ramping up support for layers based on feedback from users. So thank you for that. Most of these layers are quite simple, and haven't been added due to conversion support.
> 
> `Upsampling2D` doesn't actually need any QAT handling. You can try passing a [NoOpQuantizeConfig](https://github.com/tensorflow/model-optimization/blob/d328a642d74de85ac8d4213dfe122b94a7cbc554/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_configs.py#L44) to it as the `QuantizeConfig` and the training should just work. Let us know if the conversion has issues.
> 
> As for `Conv2DTranspose`, we still have to add support. But we can now prioritize it with this feedback. Thanks!



> Hi @Mohit-Ak @Craftsman381,
> 
> Thanks for the great feedback. We haven't added support for `Upsampling2D` and `Conv2DTranspose` yet. We are ramping up support for layers based on feedback from users. So thank you for that. Most of these layers are quite simple, and haven't been added due to conversion support.
> 
> `Upsampling2D` doesn't actually need any QAT handling. You can try passing a [NoOpQuantizeConfig](https://github.com/tensorflow/model-optimization/blob/d328a642d74de85ac8d4213dfe122b94a7cbc554/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_configs.py#L44) to it as the `QuantizeConfig` and the training should just work. Let us know if the conversion has issues.
> 
> As for `Conv2DTranspose`, we still have to add support. But we can now prioritize it with this feedback. Thanks!

Excuse me , which version can support Conv1D？

**Comment by EClemMarq** [comment]
@DuJiahao1996 , from #362, it looks like they're still working on it.
