### ISSUE TITLE
Question: number of parameter after pruning

### ISSUE THREAD

**Issue by taeheej** [tensorflow/model-optimization#373]
I checked the tutorial about pruning using mnist dataset.

The number of parameters of the original model and the pruned model is same.
Even though the file size is decreased after compressing by zip.

Is there anyway to reduce the number of parameters of a model by pruning?

**Comment by haozha111** [comment]
@liyunlu0618 , could you help take a look?

**Comment by liyunlu0618** [comment]
Pruning doesn't change the model structure so it's not meant to reduce the number of parameters, but to 'zero-out' them to save computation. Maybe you can look into distillation or other techniques that change the model architecture.
