### ISSUE TITLE
Block Sparsity not working for Squeezable Pointwise Convolution Layers

### ISSUE THREAD

**Issue by s36srini** [tensorflow/model-optimization#38]
ValueError: Block Sparsity can only be used for layers which have 2-dimensional weights. I checked the source code and saw this comment: 
`# TODO(pulkitb): Check if squeeze operations should now be removed since we are only accepting 2-D weights.`

How is pruning going to work with pointwise convolutional layers of format 1x1xiCxoC if block sparsity is only supported for 2D tensors?

**Comment by teijeong** [comment]
Hi @liyunlu0618 , can you update?

**Comment by liyunlu0618** [comment]
Duplicate of https://github.com/tensorflow/model-optimization/issues/634.
Will use that to track the feature request.
