### ISSUE TITLE
BatchNorm not in PruneRegistry

### ISSUE THREAD

**Issue by mhutti1** [tensorflow/model-optimization#386]
**Describe the bug**
```ValueError: Please initialize Prune with a supported layer. Layers should either be a PrunableLayer instance, or should be supported by the PruneRegistry. You passed: <class'tensorflow.python.keras.layers.normalization.BatchNormalization'>```

**System information**

TensorFlow installed from (source or binary): ```binary```

TensorFlow version: ```2.2.0.dev20200304```

TensorFlow Model Optimization version: ```0.3.0```

Python version: ```3.6.9```

**Describe the expected behavior**
Pruned model should be created when performing ```prune_low_magnitude```
**Describe the current behavior**
Crash.
**Code to reproduce the issue**
Using a tf.keras.layers.BatchNormalization in the model

**Additional context**
Adding tf.python.keras.layers.normalization.BatchNormalization to my registry fixed it locally.

**Comment by alanchiao** [comment]
How are you making use of BatchNormalization? With TF 2.X, we don't support usage of tf.compat.v1 ([docs](https://www.tensorflow.org/model_optimization/guide/pruning)). 

The 2.X version of Batchnormalization is located at tensorflow.python.keras.layers.normalization_v2.BatchNormalization

**Comment by alanchiao** [comment]
If you are using tf.compat.v1.keras.layers.BatchNormalization, can you switch over to tf.keras.layers.BatchNormalization?

**Comment by mhutti1** [comment]
```
import tensorflow as tf
from tensorflow.keras import layers

tf.keras.backend.set_image_data_format("channels_last")

model = tf.keras.Sequential()
model.add(layers.Conv2D(32, 3, padding='same', use_bias=False, input_shape=(height,width, 1)))
model.add(layers.BatchNormalization(center=False, scale=False))

...
```
I guess it could be an issue with tensorflow importing the wrong BatchNorm. I certainly haven't told it to use the v1 version anywhere though.

**Comment by mhutti1** [comment]
On further investigation it seems only loading the model causes this issue

```
from tensorflow.keras.models import load_model
model = load_model('model-200e.h5')
 ```

So I guess that is the root cause, and the issue is not with this library but with the model loading.

**Comment by alanchiao** [comment]
I suppose that model-200e.h5 was a model trained in TF 2.X?

**Comment by mhutti1** [comment]
Yes

**Comment by alanchiao** [comment]
I know there was an issue like this where the wrong version was being loaded.

https://github.com/tensorflow/tensorflow/commit/6766a8ee3e74ce511c271f070c57ad3846a33a17 and other commits have since fixed it and this should be fixed in 2.2.0, which was just released.

**Comment by mhutti1** [comment]
Ah ok, I'll check it out. Thanks.

**Comment by alanchiao** [comment]
If you can upgrade to the stable 2.2.0 release and still see this issue, let me know and I can escalate the issue you filed to people.

**Comment by alanchiao** [comment]
As Isaac mentioned in the other issue, upgrading to 2.2.0 fixed the problem.
