### ISSUE TITLE
model-optimization documentation for custom training loop?

### ISSUE THREAD

**Issue by luvwinnie** [tensorflow/model-optimization#387]
Hi, thank you for great work!
I see that most of the weight pruning or quantization in the [official giude](https://www.tensorflow.org/model_optimization) use model.fit method. However, I use a lot with custom training for research purpose. I hope that the official can add some examples for those people who use the custom training loop to optimize the model!

**Comment by alanchiao** [comment]
@luvwinnie: for pruning, you can refer to https://app.reviewnb.com/tensorflow/model-optimization/pull/272/files/, which is in review. For quantization, there is nothing special to consider between model.fit and custom training loop.

**Comment by alanchiao** [comment]
comprehensive_guide.ipynb in particular

**Comment by luvwinnie** [comment]
@alanchiao Thank You so much for replying and show an example for pruning weights! I search a lot on how to use the pruning with custom loop for tensorflow keras, but seems like still not many people write about it such as blog and etc except for pytorch...Anyone Thank You!

**Comment by alanchiao** [comment]
You're welcome. If you have feedback on the documentation there, feel free to directly comment on the PR.
