### ISSUE TITLE
Inference time remains unchanged

### ISSUE THREAD

**Issue by yash88600** [tensorflow/model-optimization#391]
The compression technique used for pruning converts the model into a sparse model and save's it efficiently (maybe using csr format or other) but this doesn't help in reducing the inference time as the no of parameters still remains the same?
Please correct me if i am wrong

**Comment by alanchiao** [comment]
See https://github.com/tensorflow/model-optimization/issues/173 to efforts to improve latency.

Currently, latency is not improved, as you said.
