### ISSUE TITLE
An errors on running the example：ValueError: Please initialize `Prune` with a supported layer. Layers should either be a `PrunableLayer` instance, or should be supported by the PruneRegistry. You passed: <class 'tensorflow.python.keras.layers.recurrent.LSTM'>

### ISSUE THREAD

**Issue by baiyizhangweifeng** [tensorflow/model-optimization#401]
When I run the sample code in https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/examples/sparsity/keras/imdb/imdb_lstm.py. 
There was an errors,could you help me.
Thank you very much.

**Comment by alanchiao** [comment]
This will be fixed in https://github.com/tensorflow/model-optimization/pull/414 by @psunn and be merged soon.

After it's merged, free to reopen if you continue to face the same issue.
