### ISSUE TITLE
Support for ReLU6

### ISSUE THREAD

**Issue by ankandrew** [tensorflow/model-optimization#407]
I tried to use in a keras sequential model ReLU6 from tf.nn.relu6 but when creating the quantization aware model, but it says: `unknown activation function`, is it because it is not yet supported?

To replicate this error, I ran this [example](https://www.tensorflow.org/model_optimization/guide/quantization/training_example) in colab and I changed the activation function from tf.nn.relu to tf.nn.relu6.

Are there plans to support it?

**Comment by kalaluthien** [comment]
What about use `tf.keras.layers.ReLU(6.0)` instead?
This is not a solution but a workaround, however, It worked for me before.

**Comment by ankandrew** [comment]
@kalaluthien Thanks, that works! But still would be cool if it can be accessed the same way as tf.nn.relu.
Guess it is a matter of time

**Comment by nutsiepully** [comment]
@ankandrew - Thanks for reporting the issue.

Our API is built on `tf.keras`, and in general we are directly supporting the `tf.keras` API surface/constructs and not the other core API surfaces such as `tf.nn` etc. (We might add some additional handling for convenience if it helps but largely `tf.keras` API pieces)

So, you can expect current and ongoing support for activations under `tf.keras.activations` and the activation layers in [Keras](https://keras.io/api/layers/activations/).

I'll be modifying the colab tutorial, so it uses `relu` from keras directly. And yes, the proper way to use ReLU6 is to use the layer directly. Then it will be supported out of the box.

When passing `tf.nn.relu` or any other function, Keras treats it as just a callable. So in that case, you would need to provide your own handling.
