### ISSUE TITLE
post-training integer quantization

### ISSUE THREAD

**Issue by peter197321** [tensorflow/model-optimization#413]
Prior to the addition of per-axis quantization in optimization toolkit, post-training integer quantization was used, is it possible to enforce post-training integer quantization on the model or vice-versa explicitly enforce per-axis (aka per-channel)?

Quantized models from [Hosted models](https://www.tensorflow.org/lite/guide/hosted_models) works for me but models from [Coral Edge TPU](https://coral.ai/models/) do not work.

**Comment by jianlijianli** [comment]
The post-training integer quantization do not provide controls over using per-axis or per-tensor quantization, because per-axis is added to help recover accuracy degradation for some models.

Can you please be more specific on the issue on coral? An error message would be helpful. Thanks.

**Comment by peter197321** [comment]
Yes, that's my understanding that the tool (TensorFlow Lite converter) has no control over quantization and it can not option either per-axis (per-channel) or per-tensor quantization. 

I do not use Coral Edge TPU but what I said is that quantized models for this device (edge TPU) do not work for me since models are per-axis quantized and I can't use the TensorFlow Converter either since it has no control over quantization itself.

**Comment by nutsiepully** [comment]
@peter197321 - It seems like the Coral website provides the TFLite files for the model. You don't need to use converter in that case. If there is an issue with the model files, it would be better to raise the issue on the Coral repository.
