### ISSUE TITLE
Can not load model

### ISSUE THREAD

**Issue by enoceanwei** [tensorflow/model-optimization#418]
Hi Guys,

 I am suffering a problem, I can run the demo (minist model pruning) and saved a temp files of models at last. However, when I load the model to test(example: tf.keras.models.load_model('/tmp/tmpxr7b13cr.h5')), I got a value error which is shown as below:
"
ValueError: You are trying to load a weight file containing 2 layers into a model with 0 layers.
"

Could anyone can help me? many thanks.

Regards

Wei

**Comment by alanchiao** [comment]
@enoceanwei: you haven't provided enough information to fully understand. In particular, a reproducible example would be useful.

My best guess is that you saved only the model's weights via the tf.keras.Model `save_weights`API, which should be used together with a call to the `load_weights` API, not the `load_model` API you are using. If you saved the model with `save_model` instead, you shouldn't see this issue.

**Comment by alanchiao** [comment]
Closing since inactive - if you run into this, please reopen this issue.
