### ISSUE TITLE
Add QAT support for Concatenate layer

### ISSUE THREAD

**Issue by willbattel** [tensorflow/model-optimization#419]
Referencing @nutsiepully in #372
> We are ramping up support for layers based on feedback from users. So thank you for that. Most of these layers are quite simple, and haven't been added due to conversion support.

We're using the `NoOpQuantizeConfig` workaround for now, but in the future we would love to see native support for the Keras `Concatenate` layer. Thanks!

**Comment by nutsiepully** [comment]
Hi @willbattel,

`Concatenate` already has partial support and should often just work. Could you please add your case in which it failed, so I can prioritize it accordingly.

Sometimes layer support isn't one single thing, as there are various patterns which may show up.

Thanks.

**Comment by willbattel** [comment]
Sure, let me get together some details on our usage and I'll add them here.

**Comment by nutsiepully** [comment]
@sakumoil - your code is incorrect. You are passing an instance of a tensor rather than a layer.

`tf.keras.layers.concatenate([conv2,up1])(conv3)` returns a tensor. `tf.keras.layers.concatenate([conv2,up1])` returns a layer.

**Comment by nutsiepully** [comment]
@willbattel - Since support for `Concatenate` is too broad, please add your use case here which doesn't work once you get a chance and re-open the bug. I'll close it for now.
