### ISSUE TITLE
Is there any way to apply QuantizeConfig for Model used from Keras Modelzoo?

### ISSUE THREAD

**Issue by joyalbin** [tensorflow/model-optimization#424]
**System information**                                                             
                                                                                   
- TensorFlow version (you are using): 2.2                                          
- Are you willing to contribute it (Yes/No): yes                                   
                                                                                   
I tried use predefined models from **_keras_** using _tf.keras.applications.MobileNetV2()_
                                                                                   
I could see there are provisions to configure the quantization (bits, range or algos) for each layer using _tfmot.quantization.keras.quantize_annotate_layer()_ and apply with _tfmot.quantization.keras.quantize_apply()_ 
                                                                                   
But in case of _keras.applications_ models, user is not dealing with model layers directly. So if I have set the customised _QuantizeConfig_ then what should be the approach?

**Comment by alanchiao** [comment]
See this documentation: https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide#quantize_some_layers

and use QuantizeConfig together as described in the other documentation.

**Comment by joyalbin** [comment]
Got it. Thank you very much
