### ISSUE TITLE
AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_keras_model_file'

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/model-optimization#429]
I am having one TensorFlow Keras model "model.h5". I want to generate tflite from it. I am using the below-mentioned code for that. I am using tensorflow version '2.0.0'. Later on I want to convert this model for the google coral edge tpu. 

    import tensorflow as tf
    import numpy as np
    from tensorflow import lite

    dataset_dir = "C:\\Users\\Ravi\\dataset"
    IMAGE_SIZE = 224
    saved_keras_model = "C:\\Users\\Ravi\\model.h5"

    def representative_data_gen():
      dataset_list = tf.data.Dataset.list_files(dataset_dir + '/*/*')
      for i in range(100):
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

    converter =  lite.TFLiteConverter.from_keras_model_file(saved_keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    # This ensures that if any ops can't be quantized, the converter throws an error
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    # These set the input and output tensors to uint8
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    # And this sets the representative dataset so we can quantize the activations
    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()

    with open('mobilenet_v2_1.0_224_quant.tflite', 'wb') as f:
          f.write(tflite_model)

I am getting this kind of error.

Traceback (most recent call last):

      File "C:\Users\Ravi\tflite_model.py", line 28, in <module>
        converter =  lite.TFLiteConverter.from_keras_model_file(saved_keras_model)

    AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_keras_model_file'

What can be the problem? How can I solve this issue?

**Comment by joyalbin** [comment]
@MevadaRavikumar 
You can try with below method,
```
model = tf.keras.models.load_model("Path")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
```

**Comment by suharshs** [comment]
Hi, 

The method is from_keras_model and not from_keras_model_file. 

Here are the example invocations https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter

Thanks!
