### ISSUE TITLE
Quantization aware training can not save weights  as uint8?

### ISSUE THREAD

**Issue by aa12356jm** [tensorflow/model-optimization#457]
i use tf1.x to  quantization aware training , the weights of model  can  be saved to uint8 , but tf2.x can not  save weights  as uint8,   because  the DSP need uint8  model to  accelerate the inference ,  have you the  plan to  support  unit8  ,thanks

**Comment by gargn** [comment]
@jianlijianli Can you take a look at this issue?

**Comment by ashwinmurthy** [comment]
@suharshs  Can you assign this to the right person?

**Comment by aa12356jm** [comment]
tflite have already support full int8 model on dsp,  thanks
