### ISSUE TITLE
Weight clustering: reflect original layer's name in new layer's name

### ISSUE THREAD

**Issue by alanchiao** [tensorflow/model-optimization#462]
**Motivation**

After applying clustering to a layer, having the original layer name be reflected to some degree in model.summary() helps with continuing to understand the model.

**Describe the feature**

![Screen Shot 2020-07-13 at 11 46 09 AM](https://user-images.githubusercontent.com/4323109/87341708-ef13a200-c4fe-11ea-8e4c-7417bbb10267.png)

The layer name should still mention the original layer name. 

See the `_make_layer_name` from [quantize_wrapper.py](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize_wrapper.py).

**Comment by alanchiao** [comment]
@arovir01, @Ruomei

**Comment by MohamedNourArm** [comment]
Addressed in PR #465 , output sample after the patch shown below:

<img width="234" alt="clust_wrapper" src="https://user-images.githubusercontent.com/44364397/87665862-8119e580-c75f-11ea-89b3-ed8d55cc2747.png">

**Comment by alanchiao** [comment]
Fixed in PR Mohamed pointed to.
