### ISSUE TITLE
can we use it for tensorflow model?

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/model-optimization#49]
i want to apply it for bert trained by tensorflow

**Comment by alanchiao** [comment]
See this [documentation](https://www.tensorflow.org/model_optimization/guide/pruning). It currently supports the Keras API on 1.XX and the docs will be updated as we increase support.

**Comment by Jasperty** [comment]
what i mean is that my code is based tensorflow, not keras, can i use this api to prune my model?
