### ISSUE TITLE
Use my own class as a layer to build model

### ISSUE THREAD

**Issue by taqikoma** [tensorflow/model-optimization#5]
Thanks for your great work!
I use my own Upsample class to realize Convolutional upsample. There occurs an error: 
ValueError: Unknown layer: Upsample

What should I do to deal with it? Or "model-optimization" only apply on layers written by Keras/Tensorflow?

**Comment by alanchiao** [comment]
Custom Keras layers are supported. See this documentation: https://www.tensorflow.org/model_optimization/guide/pruning/train_sparse_models#advanced_usage_patterns

Let me know if you have any questions!

**Comment by alanchiao** [comment]
https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/sparsity/keras/PrunableLayer

for the pointer to PrunableLayer. I'll update the docs to fix the broken link.

**Comment by taqikoma** [comment]
@alanchiao 
In the "Magnitude-based weight pruning with Keras" document. There are two ways to pruning. 
One is "Build a pruned model layer by layer", the other is "Prune a whole mode".
When I use the first way:
replace 
`P5 = keras.layers.Conv2D(64, kernel_size=1,strides=1,padding='same',name='C5_reduced')(C5)
P5_upsampled = layers.Upsample(name='P5_upsampled')([P5, C4])`
by
`P5=sparsity.prune_low_magnitude(keras.layers.Conv2D(64,kernel_size=1,strides=1,padding='same',name='C5_pruneded')(C5),**pruning_params)
P5_upsampled = layers.Upsample(name='P5_upsampled')([P5, C4])``
the error is:
ValueError: Layer P5_upsampled was called with an input that isn't a symbolic tensor. Received type: <class 'NoneType'>. Full input: [None, <tf.Tensor 'block4_pool/MaxPool:0' shape=(?, ?, ?, 512) dtype=float32>]. All inputs to the layer should be tensors.

Is there any fault for me in using sparsity.prune_low_magnitude() ? 
Thank you for your kind comment!

**Comment by alanchiao** [comment]
Hi. I took a look at your code snippet. I'll be updating our docs to make the functional model use case clearer.

It should be:
sparsity.prune_low_magnitude( keras.layers.Conv2D(64,kernel_size=1,strides=1,padding='same',name='C5_pruneded'), **pruning_params)(C5)

instead of:
sparsity.prune_low_magnitude( keras.layers.Conv2D(64,kernel_size=1,strides=1,padding='same',name='C5_pruneded'(C5), **pruning_params)

**Comment by alanchiao** [comment]
Closing now. If this doesn't fix your issue, please reopen this issue. Thanks!
