### ISSUE TITLE
Clustering comprehensive guide - incorrect header sizes

### ISSUE THREAD

**Issue by alanchiao** [tensorflow/model-optimization#511]
In the current iteration of [the comprehensive guide](https://www.tensorflow.org/model_optimization/guide/clustering/clustering_comprehensive_guide), the headers are the wrong sizes, resulting in an incomplete navigation side bar that doesn't show the sections on improving accuracy, etc. 

<img width="131" alt="Screen Shot 2020-08-08 at 9 35 57 AM" src="https://user-images.githubusercontent.com/4323109/89715482-ae227800-d95a-11ea-96ba-0ed41e20429a.png">

**Comment by Ruomei** [comment]
@alanchiao Just saw it. Is it urgent for the launch? I can def make the change but I do not have the permission to raise a PR without other's internal final check.
Anyone of you might be working tomorrow? @arovir01 @wwwind @psunn @akarmi

**Comment by Ruomei** [comment]
@alanchiao 
Submitted a PR [here](https://github.com/tensorflow/model-optimization/pull/512)
Thanks, @wwwind, for the review!

**Comment by alanchiao** [comment]
Thanks Ruomei and Elena. 

It wasn't urgent - I'd otherwise have created a PR to expedite things. Going forward, we probably want a more formal way of communicating such priorities though.
