### ISSUE TITLE
do you have the pruning api for tensorflow model?

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/model-optimization#52]
i use tensorflow, not keras, but i find your api is for keras

**Comment by alanchiao** [comment]
We only explicitly target the tf.keras API (see details [here](https://www.tensorflow.org/model_optimization/guide/pruning#overview)).

If you're looking for an API for TensorFlow (in 1.X), you can use https://www.tensorflow.org/api_docs/python/tf/contrib/model_pruning/Pruning. Note that no further updates will be made to that library and contrib is going away in 2.XX.
