### ISSUE TITLE
Post-training quantization 

### ISSUE THREAD

**Issue by Haoxuan-Wang** [tensorflow/model-optimization#522]
Hello, In the process of realizing post-training quantification, I chose Post-training full integer quantization. and it is  succeeded. but i  want to know  how  it  quantization.because  I need to implement it to the FPGA .  i  want  to konw How does he achieve 8-bit quantization. and  How does he implement the convolution and  pooling operation. if you know , can you Write an essay to me,thank you very much

**Comment by Haoxuan-Wang** [comment]
主要是卷积后的激活层是如何处理的，因为我采用的是RELU函数，因此它是在激活之前根据结果的最大值和最小值来计算哪些数值应该赋给什么值吗

**Comment by Haoxuan-Wang** [comment]
It's basically what happens to the activation layer after the convolution, because I'm using the RELU function, so it calculates which values should be assigned to which values according to the maximum and minimum values of the results before activation

**Comment by teijeong** [comment]
Hi, sorry for late response. Seems it's related to generic [post-training quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant). Will close this as it's not about specific model optimization techniques (e.g. QAT, pruning) in this repo. Please file a new issue if you indeed need those techniques.
