### ISSUE TITLE
Is Sigmoid activation currently supported ?

### ISSUE THREAD

**Issue by eyebies** [tensorflow/model-optimization#534]
Hi- 
Just wondering if the sigmoid activation is currently supported? I was able to train the model using modified the quantize config, however, the tflite conversion fails. 
Tensorflow - '2.4.0-dev20200907'
tfmot - 1.18.4
keras - 2.4.3
thanks!

    raise ValueError(self._CUSTOM_ACTIVATION_ERR_MSG)
ValueError: Only some Keras activations under `tf.keras.activations` are supported. For other activations, use `Quantizer` directly, and update layer config using `QuantizeConfig`.

**Comment by Ratansairohith** [comment]
@eyebies are you able to solve the issue?? I am facing the same issue!

**Comment by rilut** [comment]
@eyebies @Ratansairohith Yes I still face the same issue, cannot train using sigmoid for binary classification model. Do you have any workaround for this?

@tensorflower-gardener Hi is #569 merged in pip/pypi version?

**Comment by rilut** [comment]
@nutsiepully hi I see your PR #569, very cool. do you know when will tensorflow_model_optimization release new version in pypi? thanks

**Comment by nutsiepully** [comment]
Thanks @rilut. Glad you found it helpful.

@daverim @Xhark would know when a new release is coming.
