### ISSUE TITLE
Script for training example models(MobileNetV1, ResNet, MobileNetv2)

### ISSUE THREAD

**Issue by debapriyamaji** [tensorflow/model-optimization#535]
**System information**

- TensorFlow version :2.2
- Are you willing to contribute it : Yes

Example script for training the models from the documentation(E.g. MobilenetV1, MobileNetV2, ResNet) aren't probably published . I am unable to reproduce those results.  Is it possible to publish those scripts with all relevant hyper-parameters?

Is it also possible to **share those models as well**? The ones in TFLite hosted models  look outdated. They don't have any Fakequant node.

Regards- Debapriya

**Comment by debapriyamaji** [comment]
Hi @alanchiao ,
Is it possible to share some training script for quantization aware training? 

Regards - Debapriya

**Comment by teijeong** [comment]
Seems to be a duplicate of #133 . Let's consolidate efforts on that bug.
