### ISSUE TITLE
Saved model parameters in quantize aware training for ResNet50

### ISSUE THREAD

**Issue by NilakshanKunananthaseelan** [tensorflow/model-optimization#559]
I've created a model file for  ResNet50 pretrained model with tf model optimization tool kit. I've customized config with 8 bit for activation and 5 bits for weights.

`
import tensorflow_model_optimization as tfmot

LastValueQuantizer = tfmot.quantization.keras.quantizers.LastValueQuantizer
MovingAverageQuantizer = tfmot.quantization.keras.quantizers.MovingAverageQuantizer
class DefaultConv2DQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
   
    def get_weights_and_quantizers(self, layer):
      return [(layer.kernel, LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False))]

    def get_activations_and_quantizers(self, layer):
      return [(layer.activation, MovingAverageQuantizer(num_bits=8, symmetric=True, narrow_range=True, per_axis=False))]

    def set_quantize_weights(self, layer, quantize_weights):
      layer.kernel = quantize_weights[0]

    def set_quantize_activations(self, layer, quantize_activations):
      layer.activation = quantize_activations[0]
    
    def get_output_quantizers(self, layer):
      return []

    def get_config(self):
      return {}  

class Conv2DQuantizeConfig(DefaultConv2DQuantizeConfig):
    
    def get_weights_and_quantizers(self, layer):
      return [(layer.kernel, LastValueQuantizer(num_bits=5, symmetric=True, narrow_range=True, per_axis=False))

#Activations in Convolution Layers

class DefaultActivationQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    
    def get_activations_and_quantizers(self, layer):
      return [(layer.activation, MovingAverageQuantizer(num_bits=8, symmetric=False, narrow_range=False, per_axis=False))] 

    def set_quantize_activations(self, layer, quantize_activations):
      layer.activation = quantize_activations[0]
    
    def get_output_quantizers(self, layer):
      return []

    def get_config(self):
      return {}

class ActivationQuantizeConfig(DefaultActivationQuantizeConfig):
    
    def get_weights_and_quantizers(self, layer):
      return []
    def set_quantize_weights(self, layer, quantize_weights):
      return
    
    #Change number of bits as needed. Here same as default                                      
    def get_activations_and_quantizers (self, layer):
      return [(layer.activation, MovingAverageQuantizer(num_bits=8, symmetric=True, narrow_range=True, per_axis=False))]

                                                
#Dense Layers

class DefaultDenseQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
   
    def get_weights_and_quantizers(self, layer):
      return [(layer.kernel, LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False))]

    def get_activations_and_quantizers(self, layer):
      return [(layer.activation, MovingAverageQuantizer(num_bits=8, symmetric=False, narrow_range=False, per_axis=False))]

    def set_quantize_weights(self, layer, quantize_weights):
      layer.kernel = quantize_weights[0]

    def set_quantize_activations(self, layer, quantize_activations):
      layer.activation = quantize_activations[0]
    
    def get_output_quantizers(self, layer):
      return []

    def get_config(self):
      return {}
      
class DenseQuantizeConfig(DefaultConv2DQuantizeConfig):

    #Change number of bits as needed
    def get_weights_and_quantizers(self, layer):
      return [(layer.kernel, LastValueQuantizer(num_bits=5, symmetric=True, narrow_range=True, per_axis=False))]
    #Change number of bits as needed. Here same as default
    def get_activations_and_quantizers(self, layer):
      return [(layer.activation, MovingAverageQuantizer(num_bits=8, symmetric=True, narrow_range=True, per_axis=False))]
`

 

In the resulted .h5 file, I randomly selected a layer.
<HDF5 group "/model_weights/quant_conv2_block2_2_conv" (2 members)>
This group has two branches conv2_block2_2_conv & quant_conv2_block2_2_conv.

quant_conv2_block2_2_conv has  

kernel_max:0 0.32907793
kernel_min:0 -0.32907793
optimizer_step:0 -1
post_activation_max:0 6.874021
post_activation_min:0 -6.874021

conv2_block2_2_conv has kernel and bias.

In [tfmot quantize apply document](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization/keras/quantize_apply),it is mentioned 

> The returned model copies over weights from the original model. So while it preserves the original weights, training it will not modify the weights of the original model.

In such case do we need to create the quantized weights using the given parameters?
In my case 32 quantized levels  from kernel_min:0  to kernel_max:0

For some other layers,kernel_min:0 and kernel_max:0 are not same in magnitude. How can I grep the quantized weight values?

**Comment by NilakshanKunananthaseelan** [comment]
![model](https://user-images.githubusercontent.com/25349618/94674971-9c47ca80-0336-11eb-9549-ba95dfd2782e.png)

**Comment by ej159** [comment]
I would also like to know of a way of extracting quantized weights from quantization aware models. I guess there is a route to get them by converting to a TFLite model and then reading the buffer there but that is a bit hacky.

If I dig into the model non_trainable_weights I can see the `optimizer_step`, `kernel_min`, `kernel_max`, `post_activation_min` and `post_activation_max` variables. How can I use these variables to give the quantized weights that are used during training or in the TFLite model? These variables are also returned when get_weights() is called.

**Comment by NilakshanKunananthaseelan** [comment]
I observed that Tensorflow's Model Optimization Toolkit did range based linear quantization, in which  FP waits are taken and mapped in the desired range(quantizing to INT) and again dequantized using the quantization parameter obtained, to FP values.

So I had dumped the h5 file and manually quantize again from the quantized values.

`
import h5py
import numpy as np
import torch
import torch.nn as nn
 
f = h5py.File("resnet50_QAT.h5")
mem = [i for i in f["model_weights"]]
model_params = {}
quantized_weight = False #Save the checkpoint with quantized or dequantized weight
w_bits = 5
a_bits = 8
n_q = (2**w_bits-1) 
print((n_q//2))
p_f=1
for ele in mem:
    e = ele
    grp = f['model_weights'][ele]
    grp_type = [i for i in grp]
    if(len(grp_type)>0):
        conv_grp = f['model_weights'][ele][grp_type[0]]
        quant_grp = f['model_weights'][ele][grp_type[-1]]
        param = [i for i in conv_grp]

        if("quant" in ele):
            print("layer : {}".format(ele))
            for i in range (len(param)):
                print("{} : {}".format(param[i],conv_grp[param[i]].value.shape))
                w_deq = np.array(conv_grp[param[i]].value)
                
                if(quantized_weight and 'relu' not in ele and 'out' not in ele and 'predictions' not in ele):
                    f_w = w_deq.flatten()
                    if ('bias' in param[i]):
                        _l = 'bias'
                    elif('kernel' in param[i]):
                        _l = 'weight'
                        if(p_f==1):
                            print(w_deq)
                            p_f=2
                    print("Dequantized {} -> min : {} and max : {}".format(_l,min(f_w),max(f_w)))


                    w_scale = (quant_grp['kernel_max:0'].value - quant_grp['kernel_min:0'].value)/n_q
                    print((quant_grp['kernel_max:0'].value - quant_grp['kernel_min:0'].value)/15)
                    print("Scale : {} ".format(w_scale))

                    print("Dequantized scaled min :{} max :{}".format(min(f_w)/w_scale,max(f_w)/w_scale))
                    w_q = np.round(w_deq/(1.0*w_scale))

                    print("{} :{}".format(quant_grp['kernel_max:0'].name.split('/')[-1],quant_grp['kernel_max:0'].value))
                    print("{} :{}".format(quant_grp['kernel_min:0'].name.split('/')[-1],quant_grp['kernel_min:0'].value))
                    w_q[w_q==-0.] = 0.
                
                    w_q[w_q<-1*(n_q//2)] = -1*(n_q//2)
                    w_q[w_q>(n_q//2)] = n_q//2
                    f_wq = w_q.flatten()

                    print("QAT weight -> min : {} and max : {}".format(min(f_wq),max(f_wq)))

                    model_params[ele+'_'+param[i]] = w_q

                    print('\n')
                else: 
                    if('kernel' in param[i]):
                        _l = 'weight'
                        if(p_f==1):
                            print(w_deq)
                            p_f=2
                    model_params[ele+'_'+param[i]]  = w_deq
                    print('\n')
        else :
            for i in range (len(param)):
 
                model_params[ele+'_'+param[i]] = conv_grp[param[i]].value
 `

**Comment by teijeong** [comment]
Hi @NilakshanKunananthaseelan , sorry for late response.

Can you confirm if this is still an issue for you before we start to take a look now?

**Comment by NilakshanKunananthaseelan** [comment]
@teijeong, actually I  tried to create quantized weights manually. Then moved to use distiller library for quantization purpose. It solved my issues then.

**Comment by NilakshanKunananthaseelan** [comment]
@teijeong, actually I  tried to create quantized weights manually. Then moved to use distiller library for quantization purpose. It solved my issues then.

**Comment by WeiHao97** [comment]
Hi @NilakshanKunananthaseelan,
I am having the same issue. Could you point me to the distiller library for quantization purpose you used? Thank you very much!

**Comment by NilakshanKunananthaseelan** [comment]
https://github.com/IntelLabs/distiller
