### ISSUE TITLE
Model: Quantization Aware Training

### ISSUE THREAD

**Issue by eladc4** [tensorflow/model-optimization#595]
**Describe the bug**
Running model_quantize fails because I set the model outputs as a dictionary. tfmot assumes it's a list (see .../tensorflow_model_optimization/python/core/quantization/keras/graph_transformations/model_transformer.py at _get_output_consumers

TensorFlow version: 2.3.1

TensorFlow Model Optimization version: 0.5.0

Python version: 3.7

**Describe the expected behavior**
simple solution is to go over dict values, in case self._config['output_layers'] is a dictionary

**Describe the current behavior**
fails because it goes over the keys of the dictionary

**Comment by xhae** [comment]
Hi, sorry for the huge delay on this. Can you provide more details to reproduce this? Maybe a simple code calling model_quantize would be helpful.

**Comment by eladc4** [comment]
closing as I can't reproduce the bug now (seems to work fine in TF 2.3.1)
Thanks
