### ISSUE TITLE
From which tensorflow version onwards can quantization be applied?

### ISSUE THREAD

**Issue by sachinkmohan** [tensorflow/model-optimization#610]
Hi Team,

I am currently using tensorflow 1.14 for pruning, but I am not sure if I can apply quantization on the same version. Please help.
On pruning tensorflow guide page, the below was mentioned
> TensorFlow versions: TF 1.x for versions 1.14+ and 2.x.
But this part is missing in the quantization page. 

This [page](https://www.tensorflow.org/lite/performance/post_training_quantization) mentions explicitly that _post training quantisation_ can be applied on tensflow 1.15. 

Can you please confirm that if quantization can be only applied from tensorflow 1.15 onwards or are there any alternatives for older versions?

**Comment by teijeong** [comment]
Hi @sachinkmohan , I think the best way to resolve this is to upgrade your model to be compatible with TF 1.15, or 2.x+ for even better support. Please file issue on TensorFlow repo, or post question in StackOverflow if there are some issues preventing you from upgrading your model.
