### ISSUE TITLE
ValueError: Unknown layer: AnchorBoxes quantization

### ISSUE THREAD

**Issue by sachinkmohan** [tensorflow/model-optimization#620]
**Describe the bug**
I am applying quantization to a SSD model. The [gist](https://colab.research.google.com/gist/sachinkmohan/3e2a5563a80099ce4ee489d6cd5f38e5/tf_quantization_gist.ipynb?authuser=3) is attached. There is a custom object called "AnchorBoxes" which is added while loading the model. This works fine when I don't do quantization. But when I apply quantization, this custom object is not recognized. 

I tried a work around.

```
def apply_quantization_to_conv2D(layer):
  #print(layer)
  if isinstance(layer, tf.keras.layers.Conv2D):
    return tfmot.quantization.keras.quantize_annotate_layer(layer)
  return layer

# Use `tf.keras.models.clone_model` to apply `apply_quantization_to_dense` 
# to the layers of the model.
annotated_model = tf.keras.models.clone_model(
    model,
    clone_function=apply_quantization_to_conv2D,
)

#annotated_model.save('quantize_ready_model_20_01_Conv2D.h5', include_optimizer=True)
annotated_model.summary()
# Now that the Dense layers are annotated,
# `quantize_apply` actually makes the model quantization aware.



#quant_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
```
I commented this line `quant_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)` in the above code as it was throwing the error `ValueError: Unknown layer: AnchorBoxes`

Instead I saved the model after applying quantization to the Conv2D layers as below

```
def apply_quantization_to_conv2D(layer):
  #print(layer)
  if isinstance(layer, tf.keras.layers.Conv2D):
    return tfmot.quantization.keras.quantize_annotate_layer(layer)
  return layer

# Use `tf.keras.models.clone_model` to apply `apply_quantization_to_dense` 
# to the layers of the model.
annotated_model = tf.keras.models.clone_model(
    model,
    clone_function=apply_quantization_to_conv2D,
)


annotated_model.summary()

annotated_model.save('quantize_ready_model_20_01_Conv2D_1.h5', include_optimizer=True)
# Now that the Dense layers are annotated,
# `quantize_apply` actually makes the model quantization aware.



#quant_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
#quant_aware_model.compile(optimizer=adam, loss=ssd_loss.compute_loss)
#quant_aware_model.summary()
```

Then I loaded the model hoping that the loaded quantized model as below will have the custom_objects attached to it.

```
with tfmot.quantization.keras.quantize_scope():
    loaded_model = tf.keras.models.load_model('./quantize_ready_model_20_01_Conv2D_1.h5', custom_objects={'AnchorBoxes': AnchorBoxes})
```
Finally I applied the `quantize_apply` to the new `loaded_model` which has quantized layers.

`quant_aware_model = tfmot.quantization.keras.quantize_apply(loaded_model)`

which again resulted in the same error 

`ValueError: Unknown layer: AnchorBoxes`

**System information**

TensorFlow version (installed from source or binary): TF 2.0.0

TensorFlow Model Optimization version (installed from source or binary): 0.5.0

Python version:

**Describe the expected behavior**
When I run quantize_apply(model), the model should become quantization aware

**Describe the current behavior**
Throwing an error on the custom objects

**Code to reproduce the issue**
[gist](https://colab.research.google.com/gist/sachinkmohan/3e2a5563a80099ce4ee489d6cd5f38e5/tf_quantization_gist.ipynb?authuser=3)

**Comment by Hackerman28** [comment]
Hi. I am using the same repo to generate quantised SSD model. I've been able to run the QAT using this:
quantize_scope = tfmot.quantization.keras.quantize_scope
with quantize_scope({'AnchorBoxes': AnchorBoxes}):
  quant_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
My training has not completed so I can't comment on whether the training works but model fit throws no errors.

**Comment by sachinkmohan** [comment]
@Hackerman28 Thanks a ton bro!!! :) You just saved me a lot of work and hassle!! Wish you an awesome day ahead!! :)
Such a silly mistake I did, how dumb! :/

The mistake I did is as below. 

```
with quantize_scope(
  {'DefaultDenseQuantizeConfig': DefaultDenseQuantizeConfig,
   'CustomLayer': AnchorBoxes}):
  # Use `quantize_apply` to actually make the model quantization aware.
  quant_aware_model = tfmot.quantization.keras.quantize_apply(loaded_model)
```

Instead you are right, the correct code is below

```
with quantize_scope(
  {'DefaultDenseQuantizeConfig': DefaultDenseQuantizeConfig,
   'AnchorBoxes': AnchorBoxes}):
  # Use `quantize_apply` to actually make the model quantization aware.
  quant_aware_model = tfmot.quantization.keras.quantize_apply(loaded_model)
  ```
