### ISSUE TITLE
0.5.0 in Pypi does not match the zip in github releases

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/model-optimization#623]
**Describe the bug**
I was trying out 0.5.0 locally and found that the whl installed from [pypi](https://pypi.org/project/tensorflow-model-optimization/#files) seems to match the 0.4.0 release.

**System information**

TensorFlow version (installed from source or binary): 2.4

TensorFlow Model Optimization version (installed from source or binary): 0.5.0

Python version: 3.6, 3.8

**Code to reproduce the issue**
No code, run `pip3 install tensorflow-model-optimization`. The easiest way to see this issue is to then open up `clustering_registry.py` in a text editor and go to line 342. There should be a conditional there counting the number of trainable weights (as per 0.5.0) but it's not there.

**Comment by jiafulow** [comment]
The 0.5.0 version on [pypi](https://pypi.org/project/tensorflow-model-optimization/#history) seems to point to this https://github.com/tensorflow/model-optimization/commit/525accb4d3ed3bc6d345143fb0fa1d8faa0ce23d (Sep 13, 2020). But the 0.5.0 [tag](https://github.com/tensorflow/model-optimization/tags) on this GitHub repo points to https://github.com/tensorflow/model-optimization/commit/973f5b394a99b0a775e3b9f7178c865509a7d559 (Nov 23, 2020). It's kind of confusing.

**Comment by teijeong** [comment]
Hi @daverim , can you take a look?

**Comment by daverim** [comment]
Hi looks like the release was tagged a few weeks after the pip was updated. Unfortunately, we can't update pypi releases, only create new ones. You can find the matching release under 0.5.0.dev0 now:

`pip install tensorflow-model-optimization==0.5.0.dev0`

We could also update the tag, but this might break people who are checking out the tag, so seems like least bad solution.
