### ISSUE TITLE
Possible tolerance issue for transpose_conv

### ISSUE THREAD

**Issue by SaoirseARM** [tensorflow/model-optimization#627]
**Describe the bug**
The following unit test is failing due to a possible tolerance issue with the addition of the transpose_conv to QAT: 
https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/default_8bit/quantize_numerical_test.py#L177

**System information**

TensorFlow version (installed from source or binary): tf_nightly

TensorFlow Model Optimization version (installed from source or binary): tf_model_optimization_nightly

Python version: 3.6

**Describe the expected behavior**

The _get_conv2d_transpose_model test passes without an issue.

**Describe the current behavior**

Test fails with the following differences: 

```a = array([[[[-0.44025993,  0.6603899 ],
         [ 0.5723376 ,  0.30818176],
         [-0.39623404, -0.30818176],
       ...[-0.39623404,  0.26415586],
         [-0.22012997,  0.        ],
         [ 0.30818176, -0.26415586]]]], dtype=float32)
b = array([[[[-0.44025984,  0.        ],
         [ 0.5723378 ,  0.        ],
         [-0.39623386,  0.        ],
       ...[-0.39623386,  0.        ],
         [-0.22012992,  0.        ],
         [ 0.30818188,  0.        ]]]], dtype=float32), rtol = 0.1, atol = 0.1
msg = 'Mismatched value: a is different from b. '
```

**Comment by akarmi** [comment]
@daverim, @nutsiepully, can you please check this test?

**Comment by daverim** [comment]
@xhark, I believe you're more familiar with this, please take a look

**Comment by Xhark** [comment]
I think it's just a temporal error. Please reopen this issue if it happens for recent version.
