### ISSUE TITLE
Cannot quantize model with Batchnorm, but MobilenetV2 can

### ISSUE THREAD

**Issue by FSet89** [tensorflow/model-optimization#628]
Tensorflow v2.3.0
I defined a model using tf.keras and I want to perfrom quantization aware training in this way:

```
import tensorflow as tf
from tensorflow.keras import layers #i also tried to replace with tf.python.keras.layers.VersionAwareLayers
import tensorflow_model_optimization as tfmot

def build_model():
    inputs = tf.keras.Input()
    x = layers.Conv2D(24, 5, 2, 'relu')(inputs)
    x = layers.BatchNormalization()(x)
    # more layers...
    logits = layers.Softmax()(x)
    model = tf.keras.Model(inputs=inputs, outputs=logits)
    return model
    
model = build_model()
# training code
q_aware_model = tfmot.quantization.keras.quantize_model(model)
```
I get this error:

**RuntimeError: Layer batch_normalization_2:<class 'tensorflow.python.keras.layers.normalization_v2.BatchNormalization'> is not supported. You can quantize this layer by passing a 'tfmot.quantization.keras.QuantizeConfig' instance to the 'quantize_anotate_layer' API**

However, if I define the model as a keras [MobilenetV2](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/keras/applications/mobilenet_v2.py), which contains the same BatchNormalization layer, everything works fine. Where is the difference? How can I fix this problem?

**Comment by daverim** [comment]
The main reason is that you provided an activation to conv. The structure of your model should probably be more like
```
x = layers.Conv2D(24, 5, 2)(inputs)
bn = layers.BatchNormalization()(x)
activation = layers.Activation('relu')(bn)
```
