### ISSUE TITLE
Sparsity is not correctly checked in pruning integration test

### ISSUE THREAD

**Issue by johan-gras** [tensorflow/model-optimization#631]
**Describe the bug**
This is a bug located in [prune_integration_test.py](https://github.com/tensorflow/model-optimization/blob/4f4e5d02db5424d5cfcb822a8965023bf8d2011e/tensorflow_model_optimization/python/core/sparsity/keras/prune_integration_test.py).

This [specific function](https://github.com/tensorflow/model-optimization/blob/4f4e5d02db5424d5cfcb822a8965023bf8d2011e/tensorflow_model_optimization/python/core/sparsity/keras/prune_integration_test.py#L127) doesn't work the way intended, because:

- The model is first stripped, so there are no more pruning wrappers in the model.
- Then, the model is given to [assert_model_sparsity](https://github.com/tensorflow/model-optimization/blob/4f4e5d02db5424d5cfcb822a8965023bf8d2011e/tensorflow_model_optimization/python/core/sparsity/keras/test_utils.py#L167).
- However, this last function only asserts layers that have a pruning wrapper. Thus, the sparsity is not checked at all.

**System information**

TensorFlow version: not relevant.

TensorFlow Model Optimization version (installed from source or binary): source (master).

Python version: not relevant.

**Describe the expected behavior**
[_check_strip_pruning_matches_original](https://github.com/tensorflow/model-optimization/blob/4f4e5d02db5424d5cfcb822a8965023bf8d2011e/tensorflow_model_optimization/python/core/sparsity/keras/prune_integration_test.py#L127) should check the sparsity of the given model.

**Describe the current behavior**
[_check_strip_pruning_matches_original](https://github.com/tensorflow/model-optimization/blob/4f4e5d02db5424d5cfcb822a8965023bf8d2011e/tensorflow_model_optimization/python/core/sparsity/keras/prune_integration_test.py#L127) doesn't check the sparsity of the given model.

**Comment by teijeong** [comment]
Hi @johan-gras , sorry for late response, and thanks for reporting!

Are you willing to file a PR for fixing this?
