### ISSUE TITLE
Creating a saved_model_dir in google colab? -- Converting pb model to tflite

### ISSUE THREAD

**Issue by tcrossley17** [tensorflow/model-optimization#640]
**Describe the bug**
I am trying to run the following code in Google Colab to convert my model to tflite, but I am new to google colab and I am not sure how to create this directory since I am simply uploading my saved model to this program.

from google.colab import files
pbfile = files.upload()

%tensorflow_version 1.x
!pip install -U "tensorflow==1.15" 
import os
import tensorflow as tf
print(tf.__version__)
%cd /content
localpb = 'saved_model.pb'
saved_model_dir = os.path.join(content, "saved_model/1/")
tflite_file = 'converted_model.lite'
print("{} -> {}".format(localpb, tflite_file))
converter = tf.lite.TFLiteConverter.from_saved_model(
saved_model_dir,
input_arrays=["input_x"],

)
tflite_model = converter.convert()
open(tflite_file,'wb').write(tflite_model)

**Comment by daverim** [comment]
Seems like more of an issue with colab, you might want to ask here: [https://stackoverflow.com/questions/ask?tags=google-colaboratory](https://stackoverflow.com/questions/ask?tags=google-colaboratory)

However, if you click the folder icon on the left panel next to the table of contents, you can toggle on the file browser view.
There you can create directories by right-clicking.

You also might want to try the colab tutorial for shell commands:
https://colab.sandbox.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.05-IPython-And-Shell-Commands.ipynb
