### ISSUE TITLE
Full integer acceleration on x86

### ISSUE THREAD

**Issue by xhae** [tensorflow/model-optimization#657]
**System information**

- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): Yes

**Motivation**

Currently full-integer quantization runs fast only under ARM architecture. Having acceleration on x86 would be helpful.

**Comment by xhae** [comment]
@daverim, I remember you were related to this topic. Creating this topic to track the progress, there was a bug report related to this(https://github.com/tensorflow/model-optimization/issues/599). Can you update this when available?

**Comment by daverim** [comment]
This issue is fixed to some degree in tf-2.5 -- nightly versions were using reference implementations but now using optimized paths. On x86 some float models may be faster, but there shouldn't be a big discrepency.
