### ISSUE TITLE
can model-optimization speed up model?

### ISSUE THREAD

**Issue by Jasperty** [tensorflow/model-optimization#67]
not only compress the model, but also make it faster

**Comment by s36srini** [comment]
With regards to pruning, it can if you induce channel-wise sparsity and then use something like keras-surgeon to actually change the structure of the network. With quantization (more of a general concept, I'm unsure as to whether this package performs true quantization vs. quantize-aware), the weights are stored as integers, so operations such as matrix multiplication will be faster.

**Comment by alanchiao** [comment]
See https://www.tensorflow.org/model_optimization/guide/roadmap and https://www.tensorflow.org/model_optimization/guide/pruning#overview.

Collectively, they suggest ways (e.g. quantization aware training, framework support for sparse inference) that will speed up the model going forward.
