### ISSUE TITLE
.../api/quantization/keras/default_8bit missing from the pip package for version 0.5.0

### ISSUE THREAD

**Issue by phoenix-meadowlark** [tensorflow/model-optimization#714]
**Description**

The directory `.../site-packages/tensorflow_model_optimization/python/core/api/quantization/keras/default_8bit` is not present in the `pip` version of `tensorflow_model_optimization==0.5.0`, despite being present in the repo's [`v0.5.0` tag](https://github.com/tensorflow/model-optimization/tree/v0.5.0/tensorflow_model_optimization/python/core/api/quantization/keras). I've observed this in three desktop environments.

This causes errors like this in OSS versions of tests:

```py
  File "kws_streaming/layers/quantize.py", line 53, in quantize_layer
    scheme = tfmot.quantization.keras.default_8bit.Default8BitQuantizeScheme()
AttributeError: module 'tensorflow_model_optimization.python.core.api.quantization.keras' has no attribute 'default_8bit'
```

This can be reproduced as follows:

```shell
python -m pip install tensorflow_model_optimization==0.5.0
site_packages_dir=... # see `python -m site`
ls "${site_packages_dir?}/tensorflow_model_optimization/python/core/api/quantization/keras/"
```
```
__init__.py
__pycache__
quantizers
```

**System information**

TensorFlow version: `tf-nightly==2.6.0.dev20210519` (and `tf-nightly==2.6.0.dev20210412`)

TensorFlow Model Optimization version: `tensorflow_model_optimization==0.5.0`

Python version: `python3.8.6`

**Comment by fredrec** [comment]
Thanks for the report @phoenix-meadowlark,

Indeed it looks like that this directory is not in the pip package version `0.5.0`.
It is however present in the latest version (`0.5.1.dev0`) available [on PyPI](https://pypi.org/project/tensorflow-model-optimization/0.5.1.dev0).

`pip install --upgrade tensorflow-model-optimization==0.5.1.dev0` should fix the issue.

**Comment by phoenix-meadowlark** [comment]
Great – thanks!
