### ISSUE TITLE
Tensorflow pruning without keras

### ISSUE THREAD

**Issue by jerryho-quanta** [tensorflow/model-optimization#752]
Hi,

If I only have ckpt or pb with Tensorflow 1.5 training

sess.run(tf.global_variables_initializer())
	for i in range(iteration):
		saver.save(......)
I am using the model with tf code from git-hub without keras API building model
Is there anyway to use model-optimization for pruning my model?

Thanks,

Jerry Ho

**Comment by daverim** [comment]
Unfortunately the pruning API only supports Keras models. You can try creating a Keras model with the same structure and copy the weights manually or use distillation, but you will first have to convert your checkpoint or frozen graph to a Keras model first.

**Comment by jerryho-quanta** [comment]
Hi @daverim ,

Thanks for your reply,
I have tried if I save with keras API save/save_model to "*.h5", and it could be Keras pruning API after Keras load_model API without re-define a Keras model.
Does it mean Keras pruning ok if I could convert your checkpoint or pb to H5  without re-define a Keras model?

Do you have any reference code or suggestion for convert ckpt/pb to H5?

Thanks,

Jerry Ho
