### ISSUE TITLE
need support for Subtract layers QAT 

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/model-optimization#764]
**System information**

- TensorFlow version (you are using):2.5
- Are you willing to contribute it (Yes/No):

**Motivation**

What is the use case and how does it broadly benefits users? Prioritization and whether a feature is added is based on how it
helps the community and the feature's maintenance costs.

As examples:

1. Instead of, "Enable the technique for my model," "Enable this technique to work better with standard object detection models, including R-CNN (link) and SSD (link)" is stronger.

2. Instead of, "Try something more customized with the technique," "Implement a variant of the algorithm described in equations X and Y of this paper" is clearer.

**Describe the feature**

**Describe how the feature helps achieve the use case**

**Describe how existing APIs don't satisfy your use case (optional if obvious)**

As examples:

1. You tried using APIs X and Y and were able to do Z. However, that was not sufficient because of ...

2. You achieved your use case with the code snippet W. However, this was more difficult than it should be because of ... (e.g. ran into issue X or had
   to do Y).

I try to QAT traing my model with subtract layer ，but the log said：RuntimeError,youcan quantize this layer by passing a tfmot.quantization.keras.QuantizeConfig ,I wonder if I pass a config for this layer ,can I convert this training quant model to int8 tflite model ?

**Comment by Xhark** [comment]
I recommend to add custom quantize config that only quantize the output, (It's as same as Add.) and it might be okay to convert to tflite.  Due to It's a temporal solution, we have to consider to supports more binary ops natively.

**Comment by sunzhe09** [comment]
@Xhark I have success quant the Subtract layer ,now I have last layer not support quant——less，but I found it‘s support in quant spec list。which Api should  I use?

**Comment by sunzhe09** [comment]
I will update a new case
