### ISSUE TITLE
spasity function only work on keras sequential model/layer?

### ISSUE THREAD

**Issue by Charlie4zc** [tensorflow/model-optimization#78]
Since i'd like to use `sparsity.keras.prune_low_magnitude` on my model and failed due to unknown reason, i was wondering whether it only work on keras sequential models?
BTW my keras model has a lot skip connections , so i can only apply on pretrained models（which it works）or sequential 'block's of my model？

**Comment by alanchiao** [comment]
It currently works on functional models, though it'll throw an error for subclassed models. 

Assigning to self since I'm working on initial subclassed model support.

**Comment by alanchiao** [comment]
Closing now. 

If you're interested in subclassed model support, see this [issue](https://github.com/tensorflow/model-optimization/issues/155 ).
