### ISSUE TITLE
Tensorflow Lite convert not support UINT8 inference type anymore?

### ISSUE THREAD

**Issue by kweisamx** [tensorflow/model-optimization#809]
With Tensorflow 1.x, I can set tensorflow converter with inference_type uint8, therefore all op and weight will quantize to uint8

But In Tensorflow 2.x, I can't not set any config to uint8 anymore, It seems only int8,
I check the document only support change uint8 on input_inference type and output_inference type, but it's still use int8 op with whole model.

If tensorflow converter doesn't support uint8 in the future? Or I miss something?

Thanks.

**Comment by abattery** [comment]
To understand your contexts, why do you need to use the uint8 quantization technique over the int8 quantization?

**Comment by kweisamx** [comment]
Hi @abattery , I have some experiment code use uint8, so I just want to ensure the UINT8 still support now,

**Comment by abattery** [comment]
Currently, we do not support uint8 quantization at the recent TensorFlow version. We found that the signed integer quantization generally performs better than unsigned integer quantization.

If you want to generate the uint8 quantization model, you can use the old TensorFlow version.

**Comment by kweisamx** [comment]
HI @abattery 
Thank you, I got it.
