### ISSUE TITLE
quantization is supported only to Sequential mode? 

### ISSUE THREAD

**Issue by lovodkin93** [tensorflow/model-optimization#812]
Hello,
I wish to use your quantization model, but looking at your example. I have tried to follow your example, but it was done only on a Sequential mode of a model. The problem is, I wish to add the quantization to a Resnet50 model, which due to the residual parts isn't really Sequential. So, I was wondering if the Quantization model can be also used with a Functional Model, and if so, could you refer me to an example that shows how it is used there?
Thank you.

**Comment by abattery** [comment]
Currently, the quantization aware training supports sequential and functional based models but it does not support the subclassed models.

**Comment by abattery** [comment]
https://www.tensorflow.org/model_optimization/guide/quantization/training#api_compatibility

**Comment by lovodkin93** [comment]
> Currently, the quantization aware training supports sequential and functional based models but it does not support the subclassed models.

Hey, what do you mean by "subclassed models"?

**Comment by lovodkin93** [comment]
> https://www.tensorflow.org/model_optimization/guide/quantization/training#api_compatibility

Thanks!
This is exactly the demo I worked with, but it only has an example of a sequential based models, and no example nor explanation how to incorporate the quantization into functional based model.
Could you maybe share such  an example?
Alternatively, I saw you posted performace of ResNet50 with Quantization-Aware Training - could you maybe share the code of the model (as ResNet50, which is what I am working with, could not be converted to Sequential mode, due to the skip connections).
Thanks!
