### ISSUE TITLE
tflite converter failed to correctly convert q aware training model when set `disable_per_axis=True`

### ISSUE THREAD

**Issue by houray** [tensorflow/model-optimization#865]
1. System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu-20.04
TensorFlow installation (pip package or built from source): Pip package.
TensorFlow library (version, if pip package or github SHA, if built from source): 2.6.0

2. Code
Provide code to help us reproduce your issues using one of the following options:

Option B: Paste your code here or provide a link to a custom end-to-end colab
(You can paste links or attach files by dragging & dropping them below)
- Include code to invoke the TFLite Converter Python API and the errors.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.

```
import tensorflow as tf
import tensorflow_model_optimization as tfmot


(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
assert x_train.shape == (50000, 32, 32, 3)
assert x_test.shape == (10000, 32, 32, 3)
assert y_train.shape == (50000, 1)
assert y_test.shape == (10000, 1)
y_train = tf.squeeze(tf.one_hot(y_train, depth=10))
y_test = tf.squeeze(tf.one_hot(y_test, depth=10))


model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3), use_bias=False))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Conv2D(32, (3, 3), kernel_initializer='he_uniform', padding='same', use_bias=False, strides=2))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Activation('relu'))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu', kernel_initializer='he_uniform'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9), loss='categorical_crossentropy', metrics=['accuracy'])
#history = model.fit(x_train, y_train, epochs=100, batch_size=1024, validation_data=(x_test, y_test))


class PerTensorQuantizeScheme(tfmot.quantization.keras.default_8bit.Default8BitQuantizeScheme):
  def __init__(self):
    super(PerTensorQuantizeScheme, self).__init__(disable_per_axis=True)

annotated_model = tfmot.quantization.keras.quantize_annotate_model(model)
q_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model, scheme=PerTensorQuantizeScheme())
q_aware_model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9), loss='categorical_crossentropy', metrics=['accuracy'])
history = q_aware_model.fit(x_train, y_train, epochs=1, batch_size=1024, validation_data=(x_test, y_test))
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
open('qat_test.tflite', 'wb').write(converter.convert())
```

3. Failure after conversion
The model is converted successfully and is able to be inspected via e.g. Netron. However, It can convert the model, but the tflite model structure is totally wrong. the weights to the Conv2D are still fp32.

**Comment by daverim** [comment]
Hi, you must add 
``
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
``
before you convert, otherwise, your model will remain in float.

**Comment by tensorbuffer** [comment]
@daverim When you do converter.optimizations = [tf.lite.Optimize.DEFAULT], the tflite converted is post training quantization, not QAT. Looks like tflite can't support QAT yet.

**Comment by houray** [comment]
@daverim thank you for your comments.
After adding 
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```
the tflite model becomes a per channel quantized model, the conv2d_kernel min/max is a vector instead a value.

**Comment by rino20** [comment]
I guess this issue is resolved, feel free to reopen if there is any issue.
