### ISSUE TITLE
Pruning without training

### ISSUE THREAD

**Issue by aqibsaeed** [tensorflow/model-optimization#888]
Hi,

Is there a way to prune model without training e.g., only based on L1-norm? Thanks.

**Comment by aqibsaeed** [comment]
@alanchiao any thoughts if it is possible ?

**Comment by daverim** [comment]
We do have a way to apply pruning for inference latency and model evaluation only:

see https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/sparsity/keras/tools/evaluate_pruning.py

As for an accurate post-training pruning tool, we have had some thoughts based on distillation, but have not investigated it too much.

Please feel free to experiment and contribute if you have a good idea.
