### ISSUE TITLE
Learnable Scale Quantizer?

### ISSUE THREAD

**Issue by ice-tong** [tensorflow/model-optimization#903]
Hi, is tfmot support or will support learnable scale quantizer such as LSQ?
Thanks!

**Comment by FlamingSaint** [comment]
Hey, I am new to open source with decent knowledge in ML/DL can u point me right direction so I can start working on this issue..

**Comment by sngyhan** [comment]
Thanks for the feature request. We don't have a plan at this moment but contributions welcome.
