### ISSUE TITLE
Unreadable Notebook

### ISSUE THREAD

**Issue by mrgloom** [tensorflow/model-optimization#91]
I was unable to open `model-optimization/tensorflow_model_optimization/g3doc/guide/pruning/pruning_with_keras.ipynb`

Error:
`NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_typ...',)`

**Comment by mrgloom** [comment]
It's also broken in colab:
https://colab.research.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/pruning/pruning_with_keras.ipynb

**Comment by Mycaster** [comment]
it's caused by  json format error at line 122, you can fix it manually 

replace the content 

        "To use the pruning API, you need to install the
	`tensorflow-model-optimization` package. See
	https://github.com/tensorflow/model-optimization for what versions of
	TensorFlow the API is compatible with.\n",
with 

        "To use the pruning API, you need to install the",
        "`tensorflow-model-optimization` package. See ",
        "https://github.com/tensorflow/model-optimization for what versions of",
	"TensorFlow the API is compatible with.\n",

it's works for me

**Comment by alanchiao** [comment]
This issue has been fixed. Thanks for reporting it.
